// © 2026 Robert Reasey, South Fayette School District. Licensed CC BY-NC 4.0 (attribution required, no commercial use). See LICENSE.md.
/* ============================================================
   CYBER 1 VOCABULARY DATA — single source of truth.
   Loaded by vocab.html (the Vocabulary Lab) AND ctf.html (Capture the Flag).
   m = unit number (1-11), matching the curriculum map.
   Rebuilt from the official Unit 1-11 vocabulary sheets/handouts —
   every term here traces to those documents; off-list legacy terms
   were purged. Duplicate terms across units (e.g. Confidentiality in
   Units 8 and 11) are expected — each unit's sheet defines them
   separately.
   ============================================================ */
window.CY1_VOCAB = (function () {
  const MODULES = {
  1:"What is Cybersecurity?",
  2:"Digital Footprint & Cyber Hygiene",
  3:"Social Engineering",
  4:"Computer Number Systems",
  5:"OS Basics & Command Lines",
  6:"Network Basics",
  7:"Cyber Threats",
  8:"Intro to Security Controls",
  9:"Cryptology",
  10:"Cyber Competitions",
  11:"Intro to Cyber Frameworks"
};
  const VOCAB = [
  /* ---- UNIT 1: What is Cybersecurity? ---- */
  {m:1,t:"What is Cybersecurity?",d:"The practice of protecting systems, networks, programs, and data from digital attacks, damage, or unauthorized access."},
  {m:1,t:"The Story of Onity",d:"A famous security flaw where a hacker discovered that Onity digital hotel room locks could be easily opened using a cheap, hand-held electronic device."},
  {m:1,t:"Why Do We Need Cybersecurity?",d:"To protect sensitive data, personally identifiable information, intellectual property, and critical infrastructure from theft and damage."},
  {m:1,t:"Where Can We Find Cybersecurity?",d:"Everywhere digital technology exists — smartphones, cloud storage, smart home devices (IoT), corporate networks, and government systems."},
  {m:1,t:"Types of Attacks",d:"Methods cybercriminals use to target computers, networks, or devices to steal data or disrupt operations, such as phishing, ransomware, and DDoS."},
  {m:1,t:"Defenses Against Hacking",d:"The tools, protocols, and habits used to mitigate risk and shield systems from cyber threats, like firewalls, encryption, and security awareness training."},
  {m:1,t:"Creeper",d:"Created in 1971 and widely considered the first computer virus/worm; a non-malicious experiment that proved self-replicating code could move through a network."},
  {m:1,t:"Morris Worm",d:"Released in 1988, one of the first worms distributed via the internet; led to the first CFAA felony conviction and the first CERT."},
  {m:1,t:"ILOVEYOU Worm",d:"A 2000 phishing worm that infected over 50 million computers by emailing itself to a victim's entire address book."},
  {m:1,t:"Stuxnet",d:"A 2010 cyberweapon engineered to physically destroy centrifuges in Iran's nuclear program — the first publicly known cyberattack to cause physical destruction."},
  {m:1,t:"Yahoo Breach",d:"A series of breaches (2013–14) that compromised all 3 billion Yahoo accounts, the largest data breach in history."},
  {m:1,t:"SolarWinds",d:"A 2020 supply-chain attack that injected malicious code into software updates, compromising US government agencies and Fortune 500 companies."},
  {m:1,t:"Colonial Pipeline",d:"A 2021 ransomware attack that shut down a major US fuel pipeline, proving ransomware is a national security threat."},
  {m:1,t:"CrowdStrike Outage",d:"A 2024 global IT outage caused by a faulty security update — not a hack — that crashed 8.5 million Windows systems worldwide."},
  {m:1,t:"Cyber Threat Maps",d:"Real-time, visual representations of global cyber activity, showing active attacks, geographic origins, and targets."},
  {m:1,t:"Cyber Threat Trends",d:"The evolving patterns and tactics of cybercriminals as they adapt to new defenses and technologies."},
  {m:1,t:"Importance of Cyber Careers",d:"Cyber careers are critical because the modern economy depends on secure digital systems, yet there is a global shortage of qualified professionals to defend them."},
  {m:1,t:"Types of Cyber Careers",d:"Pathways ranging from technical defense and offense to policy, management, and auditing, such as Security Analyst, Penetration Tester, and Incident Responder."},
  {m:1,t:"Skills Needed in Cyber Careers",d:"A blend of hard technical skills (networking, scripting, system administration) and soft skills (writing, teamwork, analytical thinking under pressure)."},
  {m:1,t:"Education/Certifications Needed for Cyber Careers",d:"Entry into the field is flexible — through university degrees, technical bootcamps, or certifications like CompTIA Security+, CISSP, or CEH."},
  {m:1,t:"Passion",d:"A deep, intrinsic drive and enthusiasm for learning technology, solving puzzles, and keeping up with the rapidly evolving tech landscape."},
  {m:1,t:"Curiosity",d:"The desire to ask 'why' and 'how' that leads someone to reverse-engineer systems to find hidden vulnerabilities or unique solutions."},
  {m:1,t:"Performance",d:"The ability to execute technical tasks accurately and make sound decisions under high-stress conditions."},
  {m:1,t:"PC10 Skills",d:"A foundational framework outlining the top ten essential soft skills required for standard cyber competency."},
  {m:1,t:"Cyber Competitions",d:"Organized events where students and professionals compete to solve cybersecurity puzzles, defend simulated networks, or hack target infrastructure."},
  {m:1,t:"Cyber Ethics",d:"The code of moral behavior, responsibilities, and legal boundaries governing the use of computers, networks, and digital resources."},

  /* ---- UNIT 2: Digital Footprint & Cyber Hygiene ---- */
  {m:2,t:"Digital Footprint",d:"The collection of information that exists about a person online as a result of their activities, posts, accounts, searches, and interactions."},
  {m:2,t:"Data Permanence",d:"The idea that information placed online can remain available for a very long time, even after deletion attempts."},
  {m:2,t:"OSINT",d:"Open-Source Intelligence — gathering information from publicly available sources such as social media, public records, and search engines."},
  {m:2,t:"Cyberbullying",d:"The use of digital technologies to harass, threaten, embarrass, or target another person."},
  {m:2,t:"Doxxing",d:"Publishing or sharing someone's private information online without their permission."},
  {m:2,t:"Terms of Service",d:"The agreement that explains what information a service collects, how it's used, and what rights users give up."},
  {m:2,t:"Passwords & MFA",d:"Using long, unique passwords plus Multi-Factor Authentication to reduce the risk of account compromise."},
  {m:2,t:"Geolocation",d:"Limiting location sharing to only apps that require it and reviewing app permissions regularly to protect privacy."},
  {m:2,t:"Physical Security",d:"Locking devices when unattended, securing belongings, and avoiding sharing credentials to prevent unauthorized physical access."},
  {m:2,t:"Digital Wellness",d:"Balancing screen time, maintaining healthy online habits, and evaluating information critically to support mental health."},
  {m:2,t:"Google Hacking",d:"Using advanced search operators to locate information that may not be easily visible through normal searches."},

  /* ---- UNIT 3: Social Engineering ---- */
  {m:3,t:"Social Engineering",d:"Using psychological manipulation to trick people into revealing information or granting access, rather than hacking a system directly."},
  {m:3,t:"Phishing",d:"A social engineering attack, usually by email, that tricks a target into revealing information or clicking a malicious link."},
  {m:3,t:"Spear Phishing",d:"A targeted phishing attack aimed at a specific person or organization."},
  {m:3,t:"Baiting",d:"Luring a victim with the promise of something good, like a free download or a dropped USB drive."},
  {m:3,t:"Scareware",d:"Fake warnings or pop-ups designed to frighten a victim into installing malware or paying for fake security software."},
  {m:3,t:"Pretexting",d:"Creating a believable fake reason to contact a target and gain their trust."},
  {m:3,t:"Vishing",d:"Social engineering carried out by voice phone call."},
  {m:3,t:"Smishing",d:"Phishing carried out through SMS text messages."},
  {m:3,t:"Whaling",d:"A phishing attack that targets high-profile individuals like executives."},
  {m:3,t:"Shouldering",d:"Watching a user enter sensitive information, like a password or PIN, so it can be used later."},

  /* ---- UNIT 4: Computer Number Systems ---- */
  {m:4,t:"Computer Networks",d:"A group of connected devices that share data and resources."},
  {m:4,t:"Node",d:"Any device connected to a network."},
  {m:4,t:"Networking Protocols",d:"Rules that govern how devices communicate over a network."},
  {m:4,t:"Network Interface Card (NIC)",d:"Hardware that allows a device to connect to a network."},
  {m:4,t:"Binary System",d:"A number system that uses only 0s and 1s."},
  {m:4,t:"Digital Data",d:"Information stored and processed electronically using binary."},
  {m:4,t:"Bits",d:"The smallest unit of digital data; a single 0 or 1."},
  {m:4,t:"Byte",d:"A group of 8 bits."},
  {m:4,t:"Decimal System",d:"The number system based on ten digits (0–9)."},
  {m:4,t:"Converting Decimal to Binary",d:"Converting a decimal number to binary by repeatedly dividing by 2 and recording the remainders."},
  {m:4,t:"Converting Binary to Decimal",d:"Converting a binary number to decimal by adding the place values of the 1s."},
  {m:4,t:"Computer",d:"An electronic device that processes data according to instructions."},
  {m:4,t:"Hardware",d:"The physical components of a computer."},
  {m:4,t:"Software",d:"Programs and applications that run on a computer."},
  {m:4,t:"Input",d:"Data entered into a computer."},
  {m:4,t:"Central Processing Unit (CPU)",d:"The 'brain' of the computer that executes instructions."},
  {m:4,t:"Storage",d:"Hardware used to save data long-term."},
  {m:4,t:"Output",d:"Information produced by a computer."},
  {m:4,t:"Random Access Memory (RAM)",d:"Temporary memory used while programs are running."},
  {m:4,t:"Hard Disk Drive (HDD)",d:"A storage device that uses spinning magnetic disks."},
  {m:4,t:"Solid-State Drive (SSD)",d:"A storage device that uses flash memory with no moving parts."},
  {m:4,t:"Motherboard",d:"The main circuit board connecting all computer components."},
  {m:4,t:"Peripheral Components",d:"External devices connected to a computer, such as a webcam or printer."},
  {m:4,t:"Firmware",d:"Low-level software built into hardware."},
  {m:4,t:"Operating System (OS)",d:"Software that manages a computer's hardware and software resources."},
  {m:4,t:"Application Software",d:"Programs designed for specific user tasks."},
  {m:4,t:"Drivers",d:"Software that allows the operating system to communicate with hardware."},
  {m:4,t:"Balancing Security with Other Values",d:"Security measures must be weighed against convenience, privacy, and cost."},
  {m:4,t:"Threat and Incident Response",d:"Organizations must decide how to respond when cyber incidents occur, such as paying or refusing a ransomware demand."},
  {m:4,t:"Security Breach and Vulnerability",d:"Organizations must responsibly address weaknesses and breaches, such as patching a known software flaw."},
  {m:4,t:"Network Monitoring and User Privacy",d:"Monitoring improves security but may reduce privacy, such as tracking employee internet activity."},
  {m:4,t:"Competing Interests and Obligations",d:"Security decisions often involve conflicting priorities, like protecting data while maintaining business operations."},
  {m:4,t:"Data Storage and Encryption",d:"Organizations must decide how data is stored and protected, such as encrypting customer records."},
  {m:4,t:"IoT, Smart Grid, and Product Design",d:"Connected devices create convenience but introduce security risks, such as smart home cameras being hacked."},
  {m:4,t:"Accountability for Cybersecurity",d:"Determining who is responsible for preventing and responding to incidents."},
  {m:4,t:"Security Research and Testing",d:"Ethical questions arise when discovering or testing vulnerabilities, such as responsible disclosure of a flaw."},
  {m:4,t:"Broader Impacts of Cybersecurity Practice",d:"Cybersecurity decisions affect society, businesses, and individuals, such as a data breach exposing millions of users."},

  /* ---- UNIT 5: OS Basics & Command Lines ---- */
  {m:5,t:"Operating System (OS)",d:"Software that manages a computer's hardware and resources; Linux and Windows are two major examples with different structures and uses."},
  {m:5,t:"Linux",d:"A free, open-source operating system commonly used for servers and cybersecurity work."},
  {m:5,t:"Windows",d:"A widely used operating system developed by Microsoft, common on personal and business computers."},
  {m:5,t:"Command Prompt",d:"The classic Windows command-line interpreter used to run text-based commands."},
  {m:5,t:"PowerShell",d:"A powerful command-line shell and scripting language for Windows."},
  {m:5,t:"Virtualization",d:"Running one or more simulated computers inside a physical machine."},
  {m:5,t:"Virtual Machine",d:"A software-based computer that runs inside a physical machine, isolated from the host and other VMs."},
  {m:5,t:"Host",d:"The physical machine that runs one or more virtual machines."},
  {m:5,t:"Guest",d:"The virtual machine running inside a host."},
  {m:5,t:"Hypervisor",d:"The software layer that creates and manages virtual machines."},
  {m:5,t:"GUI",d:"Graphical User Interface — a visual way of interacting with a computer using windows, icons, and a mouse."},
  {m:5,t:"CLI",d:"Command Line Interface — controlling a computer by typing text commands rather than clicking through menus."},
  {m:5,t:"File System Navigation",d:"Commands used to move through and manage folders and files, such as pwd, cd, mkdir, and rmdir."},
  {m:5,t:"User Account Management",d:"Creating, modifying, and removing user accounts and their permissions, such as with useradd or New-LocalUser."},
  {m:5,t:"Authentication",d:"Verifying the identity of a user or device."},
  {m:5,t:"Authorization",d:"Determining what an authenticated user is allowed to do."},
  {m:5,t:"Process Management",d:"Monitoring and controlling the programs currently running on a system, using commands like ps/Get-Process or kill/Stop-Process."},

  /* ---- UNIT 6: Network Basics ---- */
  {m:6,t:"Network",d:"Two or more connected devices that can share data and resources."},
  {m:6,t:"LAN",d:"Local Area Network — a network covering a small geographic area, like a home or school, typically owned by one organization."},
  {m:6,t:"WAN",d:"Wide Area Network — a network that spans large distances, like the Internet, often using shared or leased infrastructure."},
  {m:6,t:"Client",d:"A device or program that requests services or resources from a server."},
  {m:6,t:"Server",d:"A device or program that provides services or resources to clients on a network."},
  {m:6,t:"Protocol",d:"A set of rules that governs how devices communicate over a network, such as TCP/IP or HTTP."},
  {m:6,t:"Hosts",d:"Devices connected to a network that can send or receive data, such as computers or servers."},
  {m:6,t:"Network Interface Cards (NIC)",d:"Hardware that translates a computer's data into a language the network understands, allowing it to connect."},
  {m:6,t:"Network Cables",d:"Physical media that provide a path for data to travel from one point to another."},
  {m:6,t:"Switches",d:"Devices that connect multiple devices within the same network and forward data to the correct device."},
  {m:6,t:"Routers",d:"Devices that direct traffic between different networks, ensuring data reaches the right destination."},
  {m:6,t:"Wireless Access Points",d:"Devices that allow other devices to join a wired network without a physical cable."},
  {m:6,t:"Network Topology",d:"The physical or logical arrangement of devices in a network."},
  {m:6,t:"Star Topology",d:"A topology where all devices connect to a single central hub or switch."},
  {m:6,t:"Bus Topology",d:"A topology where all devices share a single central cable."},
  {m:6,t:"Mesh Topology",d:"A topology where devices are interconnected, with multiple paths between them."},
  {m:6,t:"Ring Topology",d:"A topology where devices are connected in a closed loop, with data traveling around the ring."},
  {m:6,t:"MAC Address",d:"A hardware address permanently assigned to a network interface."},
  {m:6,t:"IP Address",d:"A unique number that identifies a device on a network."},
  {m:6,t:"Port",d:"A numbered endpoint that identifies a specific service running on a device."},
  {m:6,t:"DNS",d:"Domain Name System — the protocol that translates domain names into IP addresses."},
  {m:6,t:"HTTP",d:"The protocol used to transfer unencrypted web page data."},
  {m:6,t:"HTTPS",d:"HTTP secured with encryption to protect web traffic."},
  {m:6,t:"SSH",d:"Secure Shell — an encrypted protocol for remotely accessing a computer."},
  {m:6,t:"Telnet",d:"An older, unencrypted protocol for remotely accessing a computer."},
  {m:6,t:"FTP",d:"File Transfer Protocol — a protocol used to transfer files between computers on a network."},
  {m:6,t:"OSI Model",d:"A seven-layer model that describes how data moves through a network."},
  {m:6,t:"TCP/IP Model",d:"A four-layer model that describes how data moves across the Internet."},

  /* ---- UNIT 7: Cyber Threats ---- */
  {m:7,t:"Attack Surface",d:"The total set of points where an attacker could try to enter a system."},
  {m:7,t:"Digital Attack Surface",d:"The attack surface made up of software, networks, and digital assets that could be exploited."},
  {m:7,t:"Physical Attack Surface",d:"The attack surface made up of physical devices, hardware, and locations that could be exploited."},
  {m:7,t:"Human Attack Surface",d:"The attack surface made up of people who could be tricked or manipulated into giving an attacker access."},
  {m:7,t:"Script Kiddie",d:"A low-skilled attacker who uses tools built by others without understanding them."},
  {m:7,t:"Cyber Criminal",d:"An attacker motivated primarily by financial gain."},
  {m:7,t:"Hacktivist",d:"An attacker motivated by a social, political, or ideological cause."},
  {m:7,t:"Insider Threat",d:"A threat from someone who already has legitimate access to an organization's systems."},
  {m:7,t:"Advanced Persistent Threat (APT)",d:"A skilled, well-resourced attacker or group that maintains long-term, stealthy access to a target's network."},
  {m:7,t:"State-Sponsored",d:"An attacker backed by a government, often targeting other nations for espionage or disruption."},
  {m:7,t:"Reconnaissance",d:"The first attack phase — gathering information about a target."},
  {m:7,t:"Initial Access",d:"The attack phase where the attacker first gains entry into a target system."},
  {m:7,t:"Persistence",d:"The attack phase where the attacker maintains access to a system over time."},
  {m:7,t:"Lateral Movement",d:"The technique attackers use to move from one compromised system to another inside a network."},
  {m:7,t:"Action (on Objectives)",d:"The attack phase where the attacker carries out their final goal, such as stealing data or causing damage."},
  {m:7,t:"Evade Detection",d:"The techniques attackers use to avoid being noticed by security tools or defenders."},
  {m:7,t:"Vulnerability",d:"A weakness in a system that a threat can exploit."},
  {m:7,t:"Threat",d:"Anything with the potential to cause harm to a system or data."},
  {m:7,t:"Exploit",d:"A method or piece of code that takes advantage of a vulnerability."},
  {m:7,t:"Attack",d:"An attempt to damage, disrupt, or gain unauthorized access to a system."},
  {m:7,t:"Software Bugs",d:"Errors in code that can create unintended vulnerabilities."},
  {m:7,t:"Misconfigurations",d:"Incorrectly set up systems or software that leave a security gap."},
  {m:7,t:"Unpatched Software",d:"Software that hasn't been updated to fix known vulnerabilities."},
  {m:7,t:"Weak Authentication",d:"Login methods, like simple passwords, that are easy for an attacker to bypass."},
  {m:7,t:"Human Error",d:"Mistakes made by people that create or expose a vulnerability."},
  {m:7,t:"Zero-Day Vulnerabilities",d:"A vulnerability that is unknown to the vendor and has no patch available yet."},
  {m:7,t:"CVE",d:"Common Vulnerabilities and Exposures — a public list of known vulnerabilities with unique identifiers."},
  {m:7,t:"Virus",d:"Malware that must be activated by a user opening or running a file."},
  {m:7,t:"Worm",d:"Malware that spreads from computer to computer without human interaction."},
  {m:7,t:"Trojan",d:"Malware hidden inside software that appears harmless."},
  {m:7,t:"Logic Bomb",d:"Malicious code that stays dormant until triggered by a specific condition or date."},
  {m:7,t:"Keylogger",d:"Software or hardware that records a user's keystrokes."},
  {m:7,t:"Spyware",d:"Malware that secretly tracks a user's actions and reports back to an attacker."},
  {m:7,t:"Rootkit",d:"Malware that controls the operating system and hides itself from detection."},
  {m:7,t:"Ransomware",d:"Malware that encrypts files and demands payment for the decryption key."},
  {m:7,t:"Network Attacks",d:"Attacks that target the infrastructure and traffic of a network, such as DDoS or man-in-the-middle."},
  {m:7,t:"Device Attacks",d:"Attacks that target individual devices like phones, laptops, or IoT hardware."},
  {m:7,t:"Physical Attacks",d:"Attacks that require physical access to a system or location, such as tailgating or theft."},
  {m:7,t:"Password Attacks",d:"Attacks that attempt to guess or steal login credentials, such as brute force or credential stuffing."},
  {m:7,t:"Injection Attacks",d:"Attacks that insert malicious code into a program or database, such as SQL injection."},
  {m:7,t:"Downtime",d:"The period during which a system or service is unavailable, often due to an attack."},
  {m:7,t:"Data Breach Settlement",d:"A financial payment a company makes to resolve legal claims after exposing customer data."},
  {m:7,t:"Critical Infrastructure",d:"Systems and assets, like power grids and hospitals, that are essential to public safety and the economy."},
  {m:7,t:"Reputation",d:"An organization's public standing, often considered one of its most valuable assets after a breach."},
  {m:7,t:"Customer Churn",d:"The rate at which customers stop doing business with a company, often rising after a breach."},
  {m:7,t:"Risk Mitigation",d:"Reducing the likelihood or impact of a risk through safeguards."},
  {m:7,t:"Risk Transfer",d:"Shifting the impact of a risk to another party, such as through insurance."},
  {m:7,t:"Risk Avoidance",d:"Eliminating a risk entirely by not engaging in the activity that causes it."},
  {m:7,t:"Risk Acceptance",d:"Acknowledging a risk and choosing to proceed without additional safeguards."},

  /* ---- UNIT 8: Intro to Security Controls ---- */
  {m:8,t:"CIA Triad",d:"The foundational model for cybersecurity, used to identify areas that need protection: confidentiality, integrity, and availability."},
  {m:8,t:"Confidentiality",d:"Ensuring that data is only accessible to those authorized to see it."},
  {m:8,t:"Integrity",d:"Ensuring that data is accurate, complete, and has not been changed by unauthorized people."},
  {m:8,t:"Availability",d:"Ensuring that systems and data are accessible when needed by authorized users."},
  {m:8,t:"Security Control",d:"Any safeguard or countermeasure used to avoid, detect, or minimize security risks."},
  {m:8,t:"Physical Controls",d:"Tangible items used to prevent or detect unauthorized access to physical areas."},
  {m:8,t:"Technical Controls",d:"Hardware or software mechanisms used to protect systems."},
  {m:8,t:"Managerial Controls",d:"Policies, procedures, and guidelines created by management to manage risk."},
  {m:8,t:"Preventative Controls",d:"Controls designed to stop a security incident from happening in the first place."},
  {m:8,t:"Detective Controls",d:"Controls designed to identify that a security incident has occurred or is in progress."},
  {m:8,t:"Corrective Controls",d:"Controls used to fix a system or restore data after an incident has occurred."},
  {m:8,t:"Acceptable Use Policy (AUP)",d:"A set of rules applied by an owner/manager that restricts the way a network is used."},
  {m:8,t:"Onboarding and Offboarding",d:"Processes for adding new employees or removing access when they leave."},
  {m:8,t:"Background Checks",d:"Investigating a candidate's background before hiring them."},
  {m:8,t:"Staff Training (Awareness)",d:"Educating employees on how to spot threats like phishing — the 'human firewall.'"},
  {m:8,t:"Authentication",d:"Verifying that someone is who they say they are."},
  {m:8,t:"Authorization",d:"Determining what a user is allowed to do once they are logged in."},
  {m:8,t:"Password Policy",d:"Rules for creating and maintaining passwords, such as length and complexity."},
  {m:8,t:"Multi-Factor Authentication (MFA)",d:"Requiring two or more pieces of evidence to log in."},
  {m:8,t:"Principle of Least Privilege (PoLP)",d:"Giving users only the minimum access they need to do their job."},
  {m:8,t:"Access Control",d:"The overall process of managing who can access certain resources."},
  {m:8,t:"Biometrics",d:"Using physical characteristics to grant access, such as fingerprints or facial recognition."},
  {m:8,t:"Locks",d:"Mechanical or electronic devices used to secure doors or cabinets."},
  {m:8,t:"HVAC",d:"Environmental systems that control temperature and humidity to protect equipment."},
  {m:8,t:"Suppression System",d:"Systems designed to put out fires, often using gas instead of water, to protect hardware."},
  {m:8,t:"Cameras",d:"Video surveillance used to monitor areas, acting as both a deterrent and evidence source."},
  {m:8,t:"Motion Detectors",d:"Sensors that alert security when movement is detected in an area."},
  {m:8,t:"Security Guards",d:"Personnel hired to monitor and protect a location."},
  {m:8,t:"Firewalls",d:"Hardware or software that monitors and filters network traffic based on rules."},
  {m:8,t:"Encryption",d:"Scrambling data so it cannot be read without a key, protecting it at rest and in transit."},
  {m:8,t:"Antivirus / Anti-malware",d:"Software that scans for and removes malicious programs."},
  {m:8,t:"Patch Management",d:"The process of updating software to fix known vulnerabilities."},
  {m:8,t:"Data Backups",d:"Creating copies of data to be stored elsewhere so it can be restored if lost."},
  {m:8,t:"Network Segmentation",d:"Dividing a network into smaller, isolated sub-networks."},
  {m:8,t:"Defense-in-Depth",d:"A security strategy that uses multiple layers of defense to protect data."},
  {m:8,t:"Lateral Movement",d:"The technique hackers use to move from one system to another inside a network."},
  {m:8,t:"Privilege Escalation",d:"When a hacker gains a small amount of access and tries to gain admin-level status."},

  /* ---- UNIT 9: Cryptology ---- */
  {m:9,t:"Cryptology",d:"The umbrella study of secure communication — it encompasses both making codes and breaking them."},
  {m:9,t:"Cryptography",d:"The practice of creating codes and encryption systems to protect data."},
  {m:9,t:"Cryptanalysis",d:"The study of breaking codes or finding weaknesses in encryption."},
  {m:9,t:"Plaintext",d:"The original, readable message before it is encrypted."},
  {m:9,t:"Ciphertext",d:"The encrypted, unreadable version of a message."},
  {m:9,t:"Encryption",d:"The process of converting plaintext into ciphertext."},
  {m:9,t:"Decryption",d:"The process of converting ciphertext back into plaintext."},
  {m:9,t:"Caesar Cipher",d:"A substitution cipher where each letter is shifted a fixed number of positions; used by Julius Caesar for military correspondence."},
  {m:9,t:"VENONA",d:"A top-secret U.S. project to decrypt Soviet spy cables, which uncovered major atomic spies during the Cold War."},
  {m:9,t:"Navajo Code Talkers",d:"Marines who used the Navajo language to send secure tactical messages, providing an unbreakable code during WWII."},
  {m:9,t:"Monoalphabetic Cipher",d:"A cipher where each letter of the alphabet is replaced by one other letter or symbol, such as the Caesar or Affine cipher."},
  {m:9,t:"Polyalphabetic Cipher",d:"A cipher that uses multiple substitution alphabets for different parts of a message, such as the Vigenère cipher or Enigma."},
  {m:9,t:"One-Time Pad",d:"A cipher that uses a truly random, non-repeating key as long as the message itself."},
  {m:9,t:"Perfect Secrecy",d:"A state where ciphertext provides absolutely no information about the plaintext without the key, achievable only by a correctly used one-time pad."},
  {m:9,t:"Affine Cipher",d:"A monoalphabetic cipher that uses a math formula to map letters to other letters."},
  {m:9,t:"ROT13 Cipher",d:"A Caesar shift of exactly 13 positions."},
  {m:9,t:"Rail Fence Cipher",d:"A transposition cipher that writes the message in a zig-zag pattern."},
  {m:9,t:"Vigenère Cipher",d:"A polyalphabetic cipher that uses a keyword to determine varying shifts."},
  {m:9,t:"Enigma Machine",d:"A complex rotor machine used by the German military in WWII for polyalphabetic encryption."},
  {m:9,t:"Symmetric Encryption",d:"Encryption that uses the same key to both encrypt and decrypt — fast, but with key-sharing risk."},
  {m:9,t:"Asymmetric Encryption",d:"Encryption that uses a public key to encrypt and a private key to decrypt, solving the problem of sharing keys safely."},
  {m:9,t:"Algorithm",d:"The mathematical procedure or 'recipe' that tells a computer how to encrypt data."},
  {m:9,t:"Shared Key",d:"A secret key known only to the sender and receiver, used in symmetric encryption."},
  {m:9,t:"Public Key",d:"A key that can be shared with anyone to encrypt data to its owner."},
  {m:9,t:"Private Key",d:"A secret key held only by its owner, used to decrypt data."},
  {m:9,t:"Key Exchange Problem",d:"The difficulty of sharing a secret key without it being stolen — the reason asymmetric encryption was invented."},
  {m:9,t:"Frequency Analysis",d:"Breaking a cipher by studying how often letters or symbols appear; most effective on monoalphabetic ciphers."},

  /* ---- UNIT 10: Cyber Competitions ---- */
  {m:10,t:"OSINT",d:"The art of gathering information from publicly available sources, like social media, public records, and maps, to find clues about a person, company, or location."},
  {m:10,t:"Pivot",d:"Taking a single piece of information, like an email, and using it to find new information, like a social media profile."},
  {m:10,t:"Metadata",d:"Data about data, including hidden info like GPS coordinates embedded in a photo."},
  {m:10,t:"Dorking (Google Dorking)",d:"Using advanced search filters, like filetype: or site:, to find information not indexed for the general public."},
  {m:10,t:"Cryptography",d:"The practice of scrambling data so only authorized people can read it."},
  {m:10,t:"Steganography",d:"The practice of hiding data inside other files, like a secret message inside a photo."},
  {m:10,t:"Cipher",d:"The algorithm used to encrypt or decrypt a message."},
  {m:10,t:"Encoding",d:"Changing data format for compatibility, like Base64, not for secrecy."},
  {m:10,t:"PCAP",d:"Packet Capture — a file format used to record network traffic, like a recording of everything sent over a network."},
  {m:10,t:"HTTP Status Codes",d:"Numbers that describe the result of a web request, such as 404 (Not Found) or 200 (OK)."},
  {m:10,t:"Packet",d:"A small segment of a larger message sent over a network."},
  {m:10,t:"Web Application Exploitation",d:"Identifying and testing weaknesses in websites to make them do something they weren't designed to do."},
  {m:10,t:"SQL Injection (SQLi)",d:"An attack where malicious code is inserted into entry fields, like a login box, to trick a database into revealing information."},
  {m:10,t:"Cross-Site Scripting (XSS)",d:"Injecting malicious scripts into a trusted website that then run in another user's browser."},
  {m:10,t:"Payload",d:"The part of malware or exploit code that performs the actual malicious action."},
  {m:10,t:"Forensics",d:"The recovery, preservation, and analysis of data from devices to find evidence of what happened during a cyber event."},
  {m:10,t:"File Header (Magic Bytes)",d:"The first few bytes of a file that identify its real type, even if the file extension has been changed."},
  {m:10,t:"Hashing",d:"Using an algorithm to turn data into a unique 'digital fingerprint' — if even one bit changes, the hash changes completely."},
  {m:10,t:"Disk Image",d:"A bit-for-bit copy of a hard drive or USB stick, used so investigators don't alter the original evidence."},
  {m:10,t:"Scanning & Enumeration",d:"The reconnaissance phase of an attack — finding out which devices are on a network and what software they're running."},
  {m:10,t:"Port",d:"A virtual 'door' on a computer where specific services live."},
  {m:10,t:"Nmap",d:"The industry-standard tool used to scan a network for online devices and open ports."},
  {m:10,t:"Brute Force",d:"A trial-and-error method used to guess passwords or hidden directory names by trying many combinations."},

  /* ---- UNIT 11: Intro to Cyber Frameworks ---- */
  {m:11,t:"Confidentiality",d:"Ensuring that sensitive information is only accessed by authorized people."},
  {m:11,t:"Integrity",d:"Ensuring that data is accurate and hasn't been changed by an unauthorized person."},
  {m:11,t:"Availability",d:"Ensuring that systems and data are ready and working when users need them."},
  {m:11,t:"Authentication",d:"The process of verifying that a person is who they say they are."},
  {m:11,t:"Authorization",d:"The process of giving an authenticated user permission to access specific resources."},
  {m:11,t:"Accounting",d:"Tracking and recording what a user does while they are in a system, providing an audit trail."},
  {m:11,t:"NIST Framework",d:"A set of voluntary guidelines used by organizations to manage and reduce cybersecurity risk."},
  {m:11,t:"Govern",d:"The NIST function covering the overarching rules, roles, and responsibilities for managing security."},
  {m:11,t:"Identify",d:"The NIST function of developing an understanding of an organization's assets — you can't protect what you don't know you have."},
  {m:11,t:"Protect",d:"The NIST function of developing safeguards to ensure delivery of critical services, stopping a hack before it starts."},
  {m:11,t:"Detect",d:"The NIST function of identifying when a cybersecurity event is occurring."},
  {m:11,t:"Respond",d:"The NIST function of taking action once an incident is detected, to stop damage from spreading."},
  {m:11,t:"Recover",d:"The NIST function of restoring services that were impaired during an incident."},
  {m:11,t:"Adversary",d:"Any person or group that performs malicious acts against a system."},
  {m:11,t:"Mitre Att&ck",d:"A global, living encyclopedia of adversary tactics and techniques based on real-world hacks."},
  {m:11,t:"Tactics",d:"The high-level goal, or 'why,' behind an attacker's move, such as initial access or exfiltration."},
  {m:11,t:"Techniques",d:"The method, or 'how,' an attacker achieves their goal, such as phishing or brute force."},
  {m:11,t:"Procedures",d:"The specific tools or steps used in a real-world attack, forming a fingerprint of a particular hacker group."},
  {m:11,t:"CIS Controls",d:"A prioritized set of 18 critical security controls used to stop the most common attacks."},
  {m:11,t:"Implementation Groups",d:"Categories that help an organization decide which CIS controls fit its size and budget."},
  {m:11,t:"IG1",d:"Essential cyber hygiene for small organizations with limited resources."},
  {m:11,t:"IG2",d:"CIS controls for mid-sized organizations with some specialized IT staff."},
  {m:11,t:"IG3",d:"CIS controls for large organizations with high-security needs, such as banks or hospitals."},
  {m:11,t:"HIPAA",d:"Federal law protecting the confidentiality of patient medical data."},
  {m:11,t:"PCI DSS",d:"A private regulation by credit card companies for anyone taking card payments."},
  {m:11,t:"DTSA",d:"Federal law allowing companies to sue if their trade secrets are stolen."},
  {m:11,t:"COPPA",d:"Federal law protecting the privacy of children under the age of 13 online."},
  {m:11,t:"CFAA",d:"The primary U.S. anti-hacking law, making it a crime to access a system without authorization."}
];
  return { modules: MODULES, terms: VOCAB };
})();
