/* ============================================================
   CYBER 1 VOCABULARY DATA — single source of truth.
   Loaded by vocab.html (the Vocabulary Lab) AND ctf.html (Capture the Flag).
   m = unit number (1-11), matching the curriculum map.
   add:true = "additional module term" — not on the district's official
   vocabulary list for that unit, but useful context kept from the prior
   term set. Hidden by default in the Vocabulary Lab behind an
   "include additional terms" toggle; official terms have no `add` field.
   ============================================================ */
window.CY1_VOCAB = (function () {
  const MODULES = {
  1:"What is Cybersecurity?",
  2:"Digital Footprint & Cyber Hygiene",
  3:"Social Engineering",
  4:"Computer Number Systems",
  5:"OS Basics & Command Lines",
  6:"Network Basics",
  7:"Cyber Threats",
  8:"Intro to Security Controls",
  9:"Cryptology",
  10:"Cyber Competitions",
  11:"Intro to Cyber Frameworks"
};
  const VOCAB = [
  /* ---- UNIT 1: What is Cybersecurity? ---- */
  {m:1,t:"CIA Triad",d:"The three core security goals — Confidentiality, Integrity, and Availability — used to identify what needs protecting."},
  {m:1,t:"Creeper",d:"Created in 1971 and widely considered the first computer virus/worm; a non-malicious experiment that proved self-replicating code could move through a network."},
  {m:1,t:"Morris Worm",d:"Released in 1988, one of the first worms distributed via the internet; led to the first CFAA felony conviction and the first CERT."},
  {m:1,t:"ILOVEYOU Worm",d:"A 2000 phishing worm that infected over 50 million computers by emailing itself to a victim's entire address book."},
  {m:1,t:"Stuxnet",d:"A 2010 cyberweapon engineered to physically destroy centrifuges in Iran's nuclear program — the first publicly known cyberattack to cause physical destruction."},
  {m:1,t:"Yahoo Breach",d:"A series of breaches (2013–14) that compromised all 3 billion Yahoo accounts, the largest data breach in history."},
  {m:1,t:"SolarWinds",d:"A 2020 supply-chain attack that injected malicious code into software updates, compromising US government agencies and Fortune 500 companies."},
  {m:1,t:"Colonial Pipeline",d:"A 2021 ransomware attack that shut down a major US fuel pipeline, proving ransomware is a national security threat."},
  {m:1,t:"CrowdStrike Outage",d:"A 2024 global IT outage caused by a faulty security update — not a hack — that crashed 8.5 million Windows systems worldwide."},
  {m:1,t:"Cyber Threat Maps",d:"Real-time visualizations of global cyberattacks, showing their origins and targets."},
  {m:1,t:"Cyber Threat Trends",d:"The evolving tactics and directions of cybercriminals as they adapt to new defenses and technologies."},
  {m:1,t:"Cyber Ethics",d:"The moral principles and legal boundaries that guide responsible behavior in cybersecurity."},
  {m:1,t:"Cybersecurity",d:"The practice of protecting systems, networks, and data from digital attacks, damage, or unauthorized access.",add:true},
  {m:1,t:"Confidentiality",d:"Ensuring that only authorized people can access information.",add:true},
  {m:1,t:"Integrity",d:"Ensuring that data is accurate and has not been altered.",add:true},
  {m:1,t:"Availability",d:"Ensuring that data and services are accessible to authorized users when needed.",add:true},
  {m:1,t:"Threat",d:"Anything with the potential to cause harm to a system or data.",add:true},
  {m:1,t:"Vulnerability",d:"A weakness in a system that a threat can exploit.",add:true},
  {m:1,t:"Exploit",d:"A method or piece of code that takes advantage of a vulnerability.",add:true},
  {m:1,t:"Risk",d:"The possibility that a threat exploits a vulnerability to harm an asset.",add:true},
  {m:1,t:"Asset",d:"Anything of value to an organization, such as data, hardware, or reputation.",add:true},
  {m:1,t:"Adversary",d:"A person or group that carries out a cyberattack.",add:true},
  {m:1,t:"Authentication",d:"Verifying the identity of a user or device.",add:true},
  {m:1,t:"Authorization",d:"Determining what an authenticated user is allowed to do.",add:true},
  {m:1,t:"Attack Surface",d:"The total set of points where an attacker could try to enter a system.",add:true},
  {m:1,t:"White Hat",d:"An ethical hacker who tests systems with permission to improve security.",add:true},
  {m:1,t:"Black Hat",d:"A malicious hacker who breaks into systems illegally for gain or harm.",add:true},
  {m:1,t:"Gray Hat",d:"A hacker who acts between ethical and malicious, often without permission but not maliciously.",add:true},
  {m:1,t:"Script Kiddie",d:"A low-skilled attacker who uses tools built by others without understanding them.",add:true},
  {m:1,t:"Hacktivist",d:"An attacker motivated by a social, political, or ideological cause.",add:true},
  {m:1,t:"Insider Threat",d:"A threat from someone who already has legitimate access to an organization's systems.",add:true},
  {m:1,t:"Ethics",d:"The moral principles that guide responsible and legal behavior in cybersecurity.",add:true},

  /* ---- UNIT 2: Digital Footprint & Cyber Hygiene ---- */
  {m:2,t:"Digital Footprint",d:"The collection of information that exists about a person online as a result of their activity, posts, accounts, and searches."},
  {m:2,t:"Data Permanence",d:"The idea that information placed online can remain available for a long time, even after attempts to delete it."},
  {m:2,t:"OSINT",d:"Open-Source Intelligence — gathering information from publicly available sources such as social media, records, and search engines."},
  {m:2,t:"Cyberbullying",d:"Using digital technology to harass, threaten, embarrass, or target another person."},
  {m:2,t:"Doxxing",d:"Publishing or sharing someone's private information online without their permission."},
  {m:2,t:"Terms of Service",d:"The agreement that explains what information a service collects, how it's used, and what rights users give up."},
  {m:2,t:"Passwords & MFA",d:"Using long, unique passwords plus Multi-Factor Authentication to reduce the risk of account compromise."},
  {m:2,t:"Geolocation",d:"Identifying a device's physical location, often through GPS or IP address."},
  {m:2,t:"Physical Security",d:"Locking devices, securing belongings, and limiting who can physically reach your information."},
  {m:2,t:"Digital Wellness",d:"Balancing screen time and online habits to support mental health and productive technology use."},
  {m:2,t:"Google Hacking",d:"Using advanced search operators to find information not easily visible through a normal search, for research or exposure."},

  /* ---- UNIT 3: Social Engineering ---- */
  {m:3,t:"Social Engineering",d:"Using psychological manipulation to trick people into revealing information or granting access, rather than hacking a system directly."},
  {m:3,t:"Types of Social Engineering",d:"The range of tactics attackers use — phishing, pretexting, baiting, tailgating, and more — each exploiting a different situation."},
  {m:3,t:"Human Vulnerabilities",d:"Traits such as trust, fear, curiosity, or helpfulness that attackers exploit to manipulate their targets."},
  {m:3,t:"Social Engineering Tactics",d:"Specific techniques attackers use to manipulate targets, including impersonation, urgency, and authority."},
  {m:3,t:"Prevention and Mitigation",d:"Training, policies, and habits — like verifying requests and pausing before clicking — used to reduce the risk of a social engineering attack succeeding."},
  {m:3,t:"Phishing",d:"A social engineering attack, usually by email, that tricks a target into revealing information or clicking a malicious link."},
  {m:3,t:"Spear Phishing",d:"A targeted phishing attack aimed at a specific person or organization.",add:true},
  {m:3,t:"Whaling",d:"A phishing attack that targets high-profile individuals like executives.",add:true},
  {m:3,t:"Vishing",d:"Social engineering carried out by voice phone call.",add:true},
  {m:3,t:"Smishing",d:"Phishing carried out through SMS text messages.",add:true},
  {m:3,t:"Pretexting",d:"Creating a believable fake reason to contact a target and gain their trust.",add:true},
  {m:3,t:"Baiting",d:"Luring a victim with the promise of a good, like a free download or a dropped USB drive.",add:true},
  {m:3,t:"Tailgating",d:"Following closely behind an authorized person into a restricted area without their knowledge.",add:true},
  {m:3,t:"Piggybacking",d:"Getting an authorized person to knowingly grant you access to a restricted area.",add:true},
  {m:3,t:"Shoulder Surfing",d:"Watching a user enter sensitive information so it can be used later.",add:true},
  {m:3,t:"Dumpster Diving",d:"Searching a target's physical trash for information useful to an attack.",add:true},
  {m:3,t:"Impersonation",d:"Pretending to be someone else to gain trust or access.",add:true},
  {m:3,t:"Quid Pro Quo",d:"Offering a service or benefit in exchange for information or access.",add:true},

  /* ---- UNIT 4: Computer Number Systems ---- */
  {m:4,t:"Computer Networks",d:"A group of connected devices that share data and resources."},
  {m:4,t:"Node",d:"Any device connected to a network."},
  {m:4,t:"Networking Protocols",d:"Rules that govern how devices communicate over a network."},
  {m:4,t:"Network Interface Card (NIC)",d:"Hardware that allows a device to connect to a network."},
  {m:4,t:"Binary System",d:"A number system that uses only 0s and 1s."},
  {m:4,t:"Digital Data",d:"Information stored and processed electronically using binary."},
  {m:4,t:"Bits",d:"The smallest unit of digital data; a single 0 or 1."},
  {m:4,t:"Byte",d:"A group of 8 bits."},
  {m:4,t:"Decimal System",d:"The number system based on ten digits (0–9)."},
  {m:4,t:"Computer",d:"An electronic device that processes data according to instructions."},
  {m:4,t:"Hardware",d:"The physical components of a computer."},
  {m:4,t:"Software",d:"Programs and applications that run on a computer."},
  {m:4,t:"Input",d:"Data entered into a computer."},
  {m:4,t:"Central Processing Unit (CPU)",d:"The 'brain' of the computer that executes instructions."},
  {m:4,t:"Storage",d:"Hardware used to save data long-term."},
  {m:4,t:"Output",d:"Information produced by a computer."},
  {m:4,t:"Random Access Memory (RAM)",d:"Temporary memory used while programs are running."},
  {m:4,t:"Hard Disk Drive (HDD)",d:"A storage device that uses spinning magnetic disks."},
  {m:4,t:"Solid-State Drive (SSD)",d:"A storage device that uses flash memory with no moving parts."},
  {m:4,t:"Motherboard",d:"The main circuit board connecting all computer components."},
  {m:4,t:"Peripheral Components",d:"External devices connected to a computer, such as a webcam or printer."},
  {m:4,t:"Firmware",d:"Low-level software built into hardware."},
  {m:4,t:"Operating System",d:"Software that manages a computer's hardware and software resources."},
  {m:4,t:"Application Software",d:"Programs designed for specific user tasks."},
  {m:4,t:"Drivers",d:"Software that allows the operating system to communicate with hardware."},
  {m:4,t:"Nibble",d:"A group of 4 bits, or half a byte.",add:true},
  {m:4,t:"Hexadecimal",d:"A base-16 number system using digits 0-9 and letters A-F.",add:true},
  {m:4,t:"ASCII",d:"A standard that maps characters to numeric codes using 7 or 8 bits.",add:true},
  {m:4,t:"Unicode",d:"A universal character-encoding standard that represents text from most writing systems.",add:true},
  {m:4,t:"Encoding",d:"Converting data into a specific format for storage or transmission.",add:true},
  {m:4,t:"Boolean Logic",d:"Logic based on true/false values using AND, OR, and NOT.",add:true},
  {m:4,t:"Logic Gate",d:"A hardware element that performs a Boolean operation on its inputs.",add:true},
  {m:4,t:"Overflow",d:"An error that occurs when a value is too large to be stored in the space provided.",add:true},
  {m:4,t:"Base64",d:"An encoding that represents binary data using 64 printable characters.",add:true},
  {m:4,t:"Most Significant Bit",d:"The bit with the highest value in a binary number (the leftmost bit).",add:true},
  {m:4,t:"Octal",d:"A base-8 number system using digits 0 through 7.",add:true},

  /* ---- UNIT 5: OS Basics & Command Lines ---- */
  {m:5,t:"Linux",d:"A free, open-source operating system based on the Unix design."},
  {m:5,t:"Linux Distributions",d:"Packaged versions of Linux — such as Ubuntu, Debian, or Kali — that bundle the kernel with software and tools."},
  {m:5,t:"Command Line Interface (CLI)",d:"Controlling a computer by typing text commands rather than clicking through menus."},
  {m:5,t:"File System Structure",d:"The way an operating system organizes, names, and stores files and folders."},
  {m:5,t:"User and Group Management",d:"Creating and controlling user accounts and groups, along with their permissions."},
  {m:5,t:"Network Configuration",d:"Setting up a system's network interfaces, IP addresses, and connectivity."},
  {m:5,t:"Virtualization",d:"Running a simulated computer (a virtual machine) inside a physical one, letting one machine act as many."},
  {m:5,t:"Virtual Machines",d:"Software-based computers that run inside a physical machine, isolated from the host and other VMs."},
  {m:5,t:"GUI",d:"Graphical User Interface — a visual way of interacting with a computer using windows, icons, and a mouse."},
  {m:5,t:"Command Line Basics",d:"Foundational commands used to navigate and operate a system through the CLI, such as listing, moving, and viewing files."},
  {m:5,t:"Process Management",d:"Monitoring and controlling the programs currently running on a system."},
  {m:5,t:"Kernel",d:"The core of an operating system that manages hardware and system resources.",add:true},
  {m:5,t:"Shell",d:"A program that interprets and runs the commands a user types.",add:true},
  {m:5,t:"Bash",d:"A common Linux shell and command language.",add:true},
  {m:5,t:"Terminal",d:"A text interface used to enter commands.",add:true},
  {m:5,t:"Root",d:"The all-powerful administrator account on a Linux system.",add:true},
  {m:5,t:"Home Directory",d:"The personal folder assigned to a user account.",add:true},
  {m:5,t:"Absolute Path",d:"A file location written from the root of the file system (starting with a slash).",add:true},
  {m:5,t:"Relative Path",d:"A file location written from the current directory.",add:true},
  {m:5,t:"Permissions",d:"Settings that control who can read, write, or execute a file.",add:true},
  {m:5,t:"sudo",d:"A command that runs a task with superuser (administrator) privileges.",add:true},
  {m:5,t:"Package Manager",d:"A tool that installs, updates, and removes software.",add:true},
  {m:5,t:"Open Source",d:"Software whose source code is freely available to view and modify.",add:true},
  {m:5,t:"Man Page",d:"Built-in Linux documentation for a command, shown with the man command.",add:true},
  {m:5,t:"File Permissions (rwx)",d:"Read, write, and execute settings applied to owner, group, and others.",add:true},
  {m:5,t:"Octal Permissions",d:"Representing file permissions as numbers, such as 755 or 644.",add:true},
  {m:5,t:"Process",d:"A running instance of a program.",add:true},
  {m:5,t:"Daemon",d:"A background process that provides a service on a system.",add:true},
  {m:5,t:"Cron",d:"A Linux scheduler that runs tasks automatically at set times.",add:true},
  {m:5,t:"Log File",d:"A record of system or application events, useful for troubleshooting and security.",add:true},
  {m:5,t:"Repository",d:"A storage location from which software packages are downloaded.",add:true},
  {m:5,t:"apt",d:"A package manager used on Debian and Ubuntu Linux.",add:true},
  {m:5,t:"Partition",d:"A section of a storage drive treated as a separate unit.",add:true},
  {m:5,t:"SSH",d:"Secure Shell — an encrypted protocol for remotely accessing a computer.",add:true},
  {m:5,t:"Pipe",d:"A feature that sends the output of one command as input to another.",add:true},
  {m:5,t:"Redirection",d:"Sending command output to (or input from) a file instead of the screen.",add:true},
  {m:5,t:"grep",d:"A command that searches text for lines matching a pattern.",add:true},
  {m:5,t:"chmod",d:"A command that changes a file's permissions.",add:true},
  {m:5,t:"chown",d:"A command that changes a file's owner.",add:true},
  {m:5,t:"Logging",d:"Recording system and application events for monitoring and troubleshooting.",add:true},
  {m:5,t:"Shell Scripting",d:"Writing scripts of shell commands to automate repetitive tasks.",add:true},
  {m:5,t:"Windows",d:"A widely used operating system developed by Microsoft.",add:true},
  {m:5,t:"Registry",d:"A hierarchical database that stores Windows configuration settings.",add:true},
  {m:5,t:"Active Directory",d:"A Microsoft service that manages users, computers, and permissions on a network.",add:true},
  {m:5,t:"Domain",d:"A group of networked computers managed centrally, often by Active Directory.",add:true},
  {m:5,t:"Group Policy",d:"A Windows feature for centrally managing settings and security across many computers.",add:true},
  {m:5,t:"PowerShell",d:"A powerful command-line shell and scripting language for Windows.",add:true},
  {m:5,t:"Command Prompt (cmd)",d:"The classic Windows text command interpreter.",add:true},
  {m:5,t:"NTFS",d:"The default Windows file system, which supports permissions and encryption.",add:true},
  {m:5,t:"Task Manager",d:"A tool that shows running processes and system performance.",add:true},
  {m:5,t:"Event Viewer",d:"A tool that displays logs of system, security, and application events.",add:true},
  {m:5,t:"User Account Control (UAC)",d:"A Windows feature that asks for approval before changes that need admin rights.",add:true},
  {m:5,t:"Service",d:"A program that runs in the background to support the OS or applications.",add:true},
  {m:5,t:"Scheduled Task",d:"A job Windows runs automatically at a set time or trigger.",add:true},
  {m:5,t:"Windows Defender",d:"Microsoft's built-in anti-malware protection.",add:true},
  {m:5,t:"BitLocker",d:"A Windows feature that encrypts entire drives.",add:true},
  {m:5,t:"Local Account",d:"An account that exists only on a single computer, not on a domain.",add:true},
  {m:5,t:"Patch",d:"A software update that fixes bugs or security vulnerabilities.",add:true},
  {m:5,t:"File and Folder Permissions",d:"Settings that control which users can read, change, or run files and folders.",add:true},
  {m:5,t:"Disk Management",d:"The Windows tool for creating, formatting, and managing drive partitions.",add:true},
  {m:5,t:"Remote Management",d:"Administering a computer from another location, for example via Remote Desktop.",add:true},
  {m:5,t:"Event Logs",d:"Records of system, security, and application events kept by Windows.",add:true},
  {m:5,t:"Patch Management",d:"The process of testing and applying software updates to fix vulnerabilities.",add:true},

  /* ---- UNIT 6: Network Basics ---- */
  {m:6,t:"Network Topology",d:"The physical or logical arrangement of devices in a network, such as star, bus, or mesh."},
  {m:6,t:"Protocol",d:"A set of rules that governs how devices communicate over a network."},
  {m:6,t:"TCP/IP",d:"The core suite of protocols that powers Internet communication."},
  {m:6,t:"Network Devices",d:"Hardware such as routers, switches, and access points that build and run networks."},
  {m:6,t:"Wireless Networking",d:"Connecting devices to a network using radio signals instead of cables."},
  {m:6,t:"Network Security",d:"Protecting a network and the data on it from intrusion, misuse, or attack."},
  {m:6,t:"Virtual Private Network (VPN)",d:"An encrypted tunnel that protects traffic sent over a public network."},
  {m:6,t:"Network Performance",d:"How well a network moves data, measured by speed, latency, and reliability."},
  {m:6,t:"Hosts",d:"Devices connected to a network that can send or receive data, such as computers or servers."},
  {m:6,t:"Network",d:"Two or more connected devices that can share data.",add:true},
  {m:6,t:"LAN",d:"Local Area Network — a network covering a small area like a home or school.",add:true},
  {m:6,t:"WAN",d:"Wide Area Network — a network that spans large distances, like the Internet.",add:true},
  {m:6,t:"IP Address",d:"A unique number that identifies a device on a network.",add:true},
  {m:6,t:"IPv4",d:"The 32-bit Internet addressing scheme, written as four numbers (e.g., 192.168.1.1).",add:true},
  {m:6,t:"IPv6",d:"The newer 128-bit Internet addressing scheme that allows far more addresses.",add:true},
  {m:6,t:"MAC Address",d:"A hardware address permanently assigned to a network interface.",add:true},
  {m:6,t:"Subnet",d:"A logical subdivision of a larger network.",add:true},
  {m:6,t:"Router",d:"A device that forwards data between different networks.",add:true},
  {m:6,t:"Switch",d:"A device that connects devices within one network and forwards data by MAC address.",add:true},
  {m:6,t:"Packet",d:"A small chunk of data sent across a network.",add:true},
  {m:6,t:"TCP",d:"Transmission Control Protocol — provides reliable, ordered delivery of data.",add:true},
  {m:6,t:"UDP",d:"User Datagram Protocol — provides fast, connectionless delivery without guaranteed order.",add:true},
  {m:6,t:"DNS",d:"Domain Name System — translates domain names into IP addresses.",add:true},
  {m:6,t:"DHCP",d:"A protocol that automatically assigns IP addresses to devices.",add:true},
  {m:6,t:"Port",d:"A numbered endpoint that identifies a specific service on a device.",add:true},
  {m:6,t:"Firewall",d:"Hardware or software that allows or blocks network traffic based on rules.",add:true},
  {m:6,t:"HTTPS",d:"HTTP secured with encryption (TLS) to protect web traffic.",add:true},
  {m:6,t:"OSI Model",d:"A seven-layer model that describes how data moves through a network.",add:true},

  /* ---- UNIT 7: Cyber Threats ---- */
  {m:7,t:"Malware Types",d:"The categories of malicious software, including viruses, worms, trojans, ransomware, spyware, and rootkits."},
  {m:7,t:"Malware Techniques",d:"Methods malware uses to infect, hide, spread, or persist on a system."},
  {m:7,t:"Vulnerability Types",d:"Categories of weaknesses in a system, such as software, configuration, or human vulnerabilities."},
  {m:7,t:"Vulnerability Assessment and Scanning",d:"Systematically identifying and evaluating security weaknesses, often using automated tools."},
  {m:7,t:"Vulnerability Management",d:"The ongoing process of finding, prioritizing, and fixing vulnerabilities."},
  {m:7,t:"Threat Actors",d:"Individuals or groups responsible for carrying out a cyberattack."},
  {m:7,t:"Malware",d:"Malicious software that damages a device or gives an attacker access to it.",add:true},
  {m:7,t:"Virus",d:"Malware that must be activated by a user opening or running a file.",add:true},
  {m:7,t:"Worm",d:"Malware that spreads from computer to computer without human interaction.",add:true},
  {m:7,t:"Trojan",d:"Malware hidden inside software that appears harmless.",add:true},
  {m:7,t:"Ransomware",d:"Malware that encrypts files and demands payment for the decryption key.",add:true},
  {m:7,t:"Spyware",d:"Malware that secretly tracks a user's actions and reports back to an attacker.",add:true},
  {m:7,t:"Rootkit",d:"Malware that controls the operating system and hides itself from detection.",add:true},
  {m:7,t:"Keylogger",d:"Software or hardware that records a user's keystrokes.",add:true},
  {m:7,t:"Botnet",d:"A network of infected computers controlled by an attacker.",add:true},
  {m:7,t:"Zero-Day",d:"A vulnerability with no patch available yet.",add:true},
  {m:7,t:"Payload",d:"The part of malware that performs the malicious action.",add:true},
  {m:7,t:"Backdoor",d:"A hidden way to bypass normal authentication and access a system.",add:true},
  {m:7,t:"Privilege Escalation",d:"Gaining a higher level of access than authorized.",add:true},
  {m:7,t:"Buffer Overflow",d:"Feeding more data into memory than allotted, which can crash a system or run malicious code.",add:true},
  {m:7,t:"Cyber Kill Chain",d:"A model describing the stages of a cyberattack, from reconnaissance to actions on objectives.",add:true},
  {m:7,t:"Reconnaissance",d:"The first attack phase — gathering information about a target.",add:true},
  {m:7,t:"Weaponization",d:"Creating a deliverable malicious payload.",add:true},
  {m:7,t:"Command and Control (C2)",d:"The channel an attacker uses to remotely control compromised systems.",add:true},
  {m:7,t:"Exfiltration",d:"Stealing and transferring data out of a target's network.",add:true},
  {m:7,t:"Indicators of Compromise (IoC)",d:"Evidence in logs or systems that a breach has occurred.",add:true},

  /* ---- UNIT 8: Intro to Security Controls ---- */
  {m:8,t:"Security Control",d:"Any safeguard or countermeasure used to avoid, detect, or minimize security risk."},
  {m:8,t:"Physical Controls",d:"Tangible safeguards used to prevent or detect unauthorized physical access, such as locks or guards."},
  {m:8,t:"Technical Controls",d:"Hardware or software mechanisms used to protect systems, such as encryption or firewalls."},
  {m:8,t:"Managerial Controls",d:"Policies, procedures, and guidelines created by management to manage risk, such as an Acceptable Use Policy."},
  {m:8,t:"Preventative Controls",d:"Controls designed to stop a security incident before it happens, like a locked door."},
  {m:8,t:"Detective Controls",d:"Controls designed to identify that an incident is happening or has happened, like a security camera."},
  {m:8,t:"Corrective Controls",d:"Controls used to fix a system or restore data after an incident, like restoring from a backup."},
  {m:8,t:"Acceptable Use Policy (AUP)",d:"Rules set by an organization that restrict how a network or system may be used."},
  {m:8,t:"Onboarding and Offboarding",d:"Processes for granting access to new employees and removing it when they leave."},
  {m:8,t:"Background Checks",d:"Investigating a candidate's history before hiring them for a trusted position."},
  {m:8,t:"Staff Training (Awareness)",d:"Educating employees to recognize threats like phishing — the 'human firewall.'"},
  {m:8,t:"Password Policy",d:"Rules for creating and maintaining passwords, covering length and complexity requirements."},
  {m:8,t:"Multi-Factor Authentication (MFA)",d:"Requiring two or more pieces of evidence to verify identity before granting access."},
  {m:8,t:"Principle of Least Privilege (PoLP)",d:"Giving users only the minimum access they need to do their job."},
  {m:8,t:"Access Control",d:"The overall process of managing who can access specific resources."},
  {m:8,t:"Biometrics",d:"Using physical characteristics, like a fingerprint or face, to grant access."},
  {m:8,t:"Locks",d:"Mechanical or electronic devices used to secure doors or cabinets."},
  {m:8,t:"HVAC",d:"Environmental systems that control temperature and humidity to protect equipment."},
  {m:8,t:"Suppression System",d:"A system designed to put out fires, often using gas instead of water, to protect hardware."},
  {m:8,t:"Cameras",d:"Video surveillance used to monitor areas, acting as both a deterrent and evidence source."},
  {m:8,t:"Motion Detectors",d:"Sensors that alert security when movement is detected in a protected area."},
  {m:8,t:"Security Guards",d:"Personnel hired to monitor and protect a location."},
  {m:8,t:"Firewalls",d:"Hardware or software that monitors and filters network traffic based on rules, acting as a gatekeeper."},
  {m:8,t:"Antivirus / Anti-malware",d:"Software that scans for and removes known malicious programs."},
  {m:8,t:"Patch Management",d:"The process of testing and applying software updates to fix known vulnerabilities."},
  {m:8,t:"Data Backups",d:"Copies of data stored elsewhere so it can be restored if lost or held for ransom."},
  {m:8,t:"Network Segmentation",d:"Dividing a network into smaller, isolated sub-networks to contain a breach."},
  {m:8,t:"Defense-in-Depth",d:"A security strategy that layers multiple defenses so if one fails, another still protects the asset."},
  {m:8,t:"Lateral Movement",d:"The technique attackers use to move from one compromised system to another inside a network."},

  /* ---- UNIT 9: Cryptology ---- */
  {m:9,t:"Cryptology",d:"The umbrella study of secure communication — it encompasses both making codes and breaking them."},
  {m:9,t:"Cryptography",d:"The practice of creating codes and encryption systems to protect data."},
  {m:9,t:"Cryptanalysis",d:"The study of breaking codes or finding weaknesses in encryption."},
  {m:9,t:"Plaintext",d:"The original, readable message before it is encrypted."},
  {m:9,t:"Ciphertext",d:"The encrypted, unreadable version of a message."},
  {m:9,t:"Encryption",d:"The process of converting plaintext into ciphertext."},
  {m:9,t:"Decryption",d:"The process of converting ciphertext back into plaintext."},
  {m:9,t:"Caesar Cipher",d:"A substitution cipher where each letter is shifted a fixed number of positions; used by Julius Caesar for military correspondence."},
  {m:9,t:"VENONA",d:"A top-secret U.S. project to decrypt Soviet spy cables, which uncovered major atomic spies during the Cold War."},
  {m:9,t:"Navajo Code Talkers",d:"Marines who used the Navajo language to send secure tactical messages, providing an unbreakable code during WWII."},
  {m:9,t:"Monoalphabetic Cipher",d:"A cipher where each letter of the alphabet is replaced by one other letter or symbol, such as the Caesar or Affine cipher."},
  {m:9,t:"Polyalphabetic Cipher",d:"A cipher that uses multiple substitution alphabets for different parts of a message, such as the Vigenère cipher or Enigma."},
  {m:9,t:"One-Time Pad",d:"A cipher that uses a truly random, non-repeating key as long as the message itself."},
  {m:9,t:"Perfect Secrecy",d:"A state where ciphertext provides absolutely no information about the plaintext without the key, achievable only by a correctly used one-time pad."},
  {m:9,t:"Affine Cipher",d:"A monoalphabetic cipher that uses a math formula to map letters to other letters."},
  {m:9,t:"ROT13 Cipher",d:"A Caesar shift of exactly 13 positions."},
  {m:9,t:"Rail Fence Cipher",d:"A transposition cipher that writes the message in a zig-zag pattern."},
  {m:9,t:"Vigenère Cipher",d:"A polyalphabetic cipher that uses a keyword to determine varying shifts."},
  {m:9,t:"Enigma Machine",d:"A complex rotor machine used by the German military in WWII for polyalphabetic encryption."},
  {m:9,t:"Symmetric Encryption",d:"Encryption that uses the same key to both encrypt and decrypt — fast, but with key-sharing risk."},
  {m:9,t:"Asymmetric Encryption",d:"Encryption that uses a public key to encrypt and a private key to decrypt, solving the problem of sharing keys safely."},
  {m:9,t:"Algorithm",d:"The mathematical procedure or 'recipe' that tells a computer how to encrypt data."},
  {m:9,t:"Shared Key",d:"A secret key known only to the sender and receiver, used in symmetric encryption."},
  {m:9,t:"Public Key",d:"A key that can be shared with anyone to encrypt data to its owner."},
  {m:9,t:"Private Key",d:"A secret key held only by its owner, used to decrypt data."},
  {m:9,t:"Key Exchange Problem",d:"The difficulty of sharing a secret key without it being stolen — the reason asymmetric encryption was invented."},
  {m:9,t:"Frequency Analysis",d:"Breaking a cipher by studying how often letters or symbols appear; most effective on monoalphabetic ciphers."},
  {m:9,t:"Cipher",d:"An algorithm for performing encryption or decryption.",add:true},
  {m:9,t:"Key",d:"The secret value combined with information to encrypt or decrypt it.",add:true},
  {m:9,t:"Keyspace",d:"The total number of possible keys; a larger keyspace is harder to crack.",add:true},
  {m:9,t:"Substitution Cipher",d:"A cipher that replaces each unit of plaintext with another symbol.",add:true},
  {m:9,t:"Transposition Cipher",d:"A cipher that rearranges the order of characters without changing them.",add:true},
  {m:9,t:"Hashing",d:"Converting data into a fixed-length, irreversible value called a hash.",add:true},
  {m:9,t:"Salt",d:"Random data added to a password before hashing so identical passwords hash differently.",add:true},
  {m:9,t:"Steganography",d:"Hiding a message inside another file, such as an image, so its existence is concealed.",add:true},
  {m:9,t:"Key Management",d:"The secure creation, distribution, storage, and retirement of cryptographic keys.",add:true},

  /* ---- UNIT 10: Cyber Competitions ---- */
  {m:10,t:"Cyber Competitions",d:"Gamified events where students apply technical skills to solve realistic security problems, protect networks, or investigate digital evidence."},
  {m:10,t:"Competition Formats",d:"The structured style of an event — Capture the Flag (jeopardy-style puzzles) or Defense/Offense (live-action network simulation)."},
  {m:10,t:"NCL Mindsets",d:"The core cyber mindsets — Passion, Curiosity, and Performance — plus the PC10 skills like documentation and ethical decision-making."},
  {m:10,t:"Competition Topics",d:"Challenge categories such as OSINT, cryptography, and web application exploitation, mapped to CompTIA Security+ domains."},
  {m:10,t:"Pivot",d:"Taking one piece of information, like an email, and using it to find new information, like a social media profile."},
  {m:10,t:"Metadata",d:"Data about data, including hidden info like GPS coordinates embedded in a photo."},
  {m:10,t:"Dorking (Google Dorking)",d:"Using advanced search filters, like filetype: or site:, to find information not indexed for the general public."},
  {m:10,t:"Encoding vs. Encryption",d:"Encoding changes data format for compatibility (like Base64); encryption scrambles data so only key-holders can read it."},
  {m:10,t:"Log Analysis & Network Traffic",d:"Examining records of system events or data packets moving across a network."},
  {m:10,t:"PCAP",d:"Packet Capture — a file format used to record network traffic, like a recording of everything sent over a network."},
  {m:10,t:"HTTP Status Codes",d:"Numbers that describe the result of a web request, such as 404 (Not Found) or 200 (OK)."},
  {m:10,t:"Web Application Exploitation",d:"Identifying and testing weaknesses in websites so they do something they weren't designed to do."},
  {m:10,t:"SQL Injection",d:"An attack that inserts malicious code into an entry field, like a login box, to trick a database into revealing information."},
  {m:10,t:"Cross-Site Scripting (XSS)",d:"Injecting malicious scripts into a trusted website that then run in another user's browser."},
  {m:10,t:"Forensics",d:"Recovering, preserving, and analyzing data from devices to find evidence of what happened during a cyber event."},
  {m:10,t:"File Header (Magic Bytes)",d:"The first few bytes of a file that identify its real type, even if the file extension has been changed."},
  {m:10,t:"Disk Image",d:"A bit-for-bit copy of a hard drive or USB stick, used so investigators don't alter the original evidence."},
  {m:10,t:"Scanning & Enumeration",d:"The reconnaissance phase of finding out which devices are on a network and which services they run."},
  {m:10,t:"Nmap",d:"The industry-standard tool used to scan a network for online devices and open ports."},
  {m:10,t:"Brute Force",d:"A trial-and-error method used to guess passwords or hidden directory names by trying many combinations quickly."},
  {m:10,t:"OSINT Tools",d:"Resources like Google Maps, TinEye, or Wayback Machine used to find locations or archived versions of websites."},
  {m:10,t:"CyberChef",d:"A web-based 'cyber Swiss Army knife' used to encode, decode, and analyze data."},
  {m:10,t:"TCPDUMP",d:"A command-line tool used to capture and analyze network traffic packets."},
  {m:10,t:"Capture the Flag (CTF)",d:"A cybersecurity competition where players solve challenges to find hidden flags.",add:true},
  {m:10,t:"National Cyber League (NCL)",d:"A national CTF competition for students to practice real cybersecurity skills.",add:true},
  {m:10,t:"Flag",d:"A secret string players must find to prove they solved a challenge.",add:true},
  {m:10,t:"Cyber Range",d:"A safe, simulated environment for practicing cybersecurity skills.",add:true},
  {m:10,t:"NCL Gym",d:"The NCL practice environment where players train before the games.",add:true},
  {m:10,t:"Password Cracking",d:"Recovering passwords from stored or captured data, often using tools.",add:true},
  {m:10,t:"Wireshark",d:"A tool that captures and analyzes network traffic.",add:true},
  {m:10,t:"Writeup",d:"A written explanation of how a challenge was solved.",add:true},
  {m:10,t:"Penetration Testing",d:"Authorized simulated attacks used to find and fix security weaknesses.",add:true},
  {m:10,t:"Incident Response",d:"The organized process of detecting, containing, and recovering from a cyberattack.",add:true},
  {m:10,t:"Cyber Threat Intelligence",d:"Collected information about attackers and threats used to improve defenses.",add:true},

  /* ---- UNIT 11: Intro to Cyber Frameworks ---- */
  {m:11,t:"Confidentiality",d:"Ensuring that sensitive information is only accessed by authorized people."},
  {m:11,t:"Integrity",d:"Ensuring that data is accurate and hasn't been changed by an unauthorized person."},
  {m:11,t:"Availability",d:"Ensuring that systems and data are ready and working when users need them."},
  {m:11,t:"Authentication",d:"The process of verifying that a person is who they say they are."},
  {m:11,t:"Authorization",d:"The process of giving an authenticated user permission to access specific resources."},
  {m:11,t:"Accounting",d:"Tracking and recording what a user does while they are in a system, providing an audit trail."},
  {m:11,t:"NIST Framework",d:"A set of voluntary guidelines used by organizations to manage and reduce cybersecurity risk."},
  {m:11,t:"Govern",d:"The NIST function covering the overarching rules, roles, and responsibilities for managing security."},
  {m:11,t:"Identify",d:"The NIST function of developing an understanding of an organization's assets — you can't protect what you don't know you have."},
  {m:11,t:"Protect",d:"The NIST function of developing safeguards to ensure delivery of critical services, stopping a hack before it starts."},
  {m:11,t:"Detect",d:"The NIST function of identifying when a cybersecurity event is occurring."},
  {m:11,t:"Respond",d:"The NIST function of taking action once an incident is detected, to stop damage from spreading."},
  {m:11,t:"Recover",d:"The NIST function of restoring services that were impaired during an incident."},
  {m:11,t:"Adversary",d:"Any person or group that performs malicious acts against a system."},
  {m:11,t:"Mitre Att&ck",d:"A global, living encyclopedia of adversary tactics and techniques based on real-world hacks."},
  {m:11,t:"Tactics",d:"The high-level goal, or 'why,' behind an attacker's move, such as initial access or exfiltration."},
  {m:11,t:"Techniques",d:"The method, or 'how,' an attacker achieves their goal, such as phishing or brute force."},
  {m:11,t:"Procedures",d:"The specific tools or steps used in a real-world attack, forming a fingerprint of a particular hacker group."},
  {m:11,t:"CIS Controls",d:"A prioritized set of 18 critical security controls used to stop the most common attacks."},
  {m:11,t:"Implementation Groups",d:"Categories that help an organization decide which CIS controls fit its size and budget."},
  {m:11,t:"IG1",d:"Essential cyber hygiene for small organizations with limited resources."},
  {m:11,t:"IG2",d:"CIS controls for mid-sized organizations with some specialized IT staff."},
  {m:11,t:"IG3",d:"CIS controls for large organizations with high-security needs, such as banks or hospitals."},
  {m:11,t:"HIPAA",d:"Federal law protecting the confidentiality of patient medical data."},
  {m:11,t:"PCI DSS",d:"A private regulation by credit card companies for anyone taking card payments."},
  {m:11,t:"DTSA",d:"Federal law allowing companies to sue if their trade secrets are stolen."},
  {m:11,t:"COPPA",d:"Federal law protecting the privacy of children under the age of 13 online."},
  {m:11,t:"CFAA",d:"The primary U.S. anti-hacking law, making it a crime to access a system without authorization."}
];
  return { modules: MODULES, terms: VOCAB };
})();
