/* ============================================================
   CYBER 1 VOCABULARY DATA — single source of truth.
   Loaded by vocab.html (the Vocabulary Lab) AND ctf.html (Capture the Flag).
   Edit terms here; both pages update. m = module number (1-13).
   ============================================================ */
window.CY1_VOCAB = (function () {
  const MODULES = {
  1:"What is Cybersecurity?",
  2:"Cybersecurity Ethics",
  3:"Computer Number Systems",
  4:"Intro to Cryptology",
  5:"Social Engineering",
  6:"Intro to Linux",
  7:"Linux System Administration",
  8:"Windows System Administration",
  9:"National Cyber League",
  10:"Network Basics",
  11:"Malware, Vulnerabilities, Exploits & Cyber Kill Chain",
  12:"SQL and Databases",
  13:"Preparing for Cyber II"
};
  const VOCAB = [
  {m:1,t:"Cybersecurity",d:"The practice of protecting systems, networks, and data from digital attacks, damage, or unauthorized access."},
  {m:1,t:"Confidentiality",d:"Ensuring that only authorized people can access information."},
  {m:1,t:"Integrity",d:"Ensuring that data is accurate and has not been altered."},
  {m:1,t:"Availability",d:"Ensuring that data and services are accessible to authorized users when needed."},
  {m:1,t:"CIA Triad",d:"The three core goals of security — Confidentiality, Integrity, and Availability."},
  {m:1,t:"Threat",d:"Anything with the potential to cause harm to a system or data."},
  {m:1,t:"Vulnerability",d:"A weakness in a system that a threat can exploit."},
  {m:1,t:"Exploit",d:"A method or piece of code that takes advantage of a vulnerability."},
  {m:1,t:"Risk",d:"The possibility that a threat exploits a vulnerability to harm an asset."},
  {m:1,t:"Asset",d:"Anything of value to an organization, such as data, hardware, or reputation."},
  {m:1,t:"Adversary",d:"A person or group that carries out a cyberattack."},
  {m:1,t:"Authentication",d:"Verifying the identity of a user or device."},
  {m:1,t:"Authorization",d:"Determining what an authenticated user is allowed to do."},
  {m:1,t:"Attack Surface",d:"The total set of points where an attacker could try to enter a system."},
  {m:2,t:"White Hat",d:"An ethical hacker who tests systems with permission to improve security."},
  {m:2,t:"Black Hat",d:"A malicious hacker who breaks into systems illegally for gain or harm."},
  {m:2,t:"Gray Hat",d:"A hacker who acts between ethical and malicious, often without permission but not maliciously."},
  {m:2,t:"Script Kiddie",d:"A low-skilled attacker who uses tools built by others without understanding them."},
  {m:2,t:"Hacktivist",d:"An attacker motivated by a social, political, or ideological cause."},
  {m:2,t:"Insider Threat",d:"A threat from someone who already has legitimate access to an organization's systems."},
  {m:2,t:"Ethics",d:"The moral principles that guide responsible and legal behavior in cybersecurity."},
  {m:3,t:"Binary",d:"A base-2 number system that represents data using only 0s and 1s."},
  {m:3,t:"Bit",d:"The smallest unit of data in a computer, a single 0 or 1."},
  {m:3,t:"Byte",d:"A group of 8 bits."},
  {m:3,t:"Nibble",d:"A group of 4 bits, or half a byte."},
  {m:3,t:"Decimal",d:"The base-10 number system people use every day, digits 0 through 9."},
  {m:3,t:"Hexadecimal",d:"A base-16 number system using digits 0-9 and letters A-F."},
  {m:3,t:"ASCII",d:"A standard that maps characters to numeric codes using 7 or 8 bits."},
  {m:3,t:"Unicode",d:"A universal character-encoding standard that represents text from most writing systems."},
  {m:3,t:"Encoding",d:"Converting data into a specific format for storage or transmission."},
  {m:3,t:"Boolean Logic",d:"Logic based on true/false values using AND, OR, and NOT."},
  {m:3,t:"Logic Gate",d:"A hardware element that performs a Boolean operation on its inputs."},
  {m:3,t:"Overflow",d:"An error that occurs when a value is too large to be stored in the space provided."},
  {m:3,t:"CPU",d:"The Central Processing Unit — the hardware that executes program instructions."},
  {m:3,t:"RAM",d:"Random Access Memory — fast, temporary storage used while programs run."},
  {m:3,t:"Operating System",d:"System software that manages hardware and runs applications."},
  {m:3,t:"Base64",d:"An encoding that represents binary data using 64 printable characters."},
  {m:3,t:"Most Significant Bit",d:"The bit with the highest value in a binary number (the leftmost bit)."},
  {m:3,t:"Octal",d:"A base-8 number system using digits 0 through 7."},
  {m:4,t:"Cryptology",d:"The study of secure communication, covering both making and breaking codes."},
  {m:4,t:"Cryptography",d:"The practice of hiding information so only authorized parties can read it."},
  {m:4,t:"Cryptanalysis",d:"The study of breaking codes and ciphers to reveal hidden information."},
  {m:4,t:"Cipher",d:"An algorithm for performing encryption or decryption."},
  {m:4,t:"Plaintext",d:"The original readable information before it is encrypted."},
  {m:4,t:"Ciphertext",d:"The unreadable output produced by an encryption algorithm."},
  {m:4,t:"Encryption",d:"The process of converting readable information into an unreadable form."},
  {m:4,t:"Decryption",d:"Reversing encryption to retrieve the original information."},
  {m:4,t:"Key",d:"The secret value combined with information to encrypt or decrypt it."},
  {m:4,t:"Keyspace",d:"The total number of possible keys; a larger keyspace is harder to crack."},
  {m:4,t:"Symmetric Encryption",d:"Encryption that uses the same key to both encrypt and decrypt."},
  {m:4,t:"Asymmetric Encryption",d:"Encryption that uses a public/private key pair, one key to encrypt and the other to decrypt."},
  {m:4,t:"Public Key",d:"The freely published key in an asymmetric pair, used to encrypt data to its owner."},
  {m:4,t:"Private Key",d:"The secret key in an asymmetric pair, kept safe and used to decrypt data."},
  {m:4,t:"Caesar Cipher",d:"A substitution cipher that shifts each letter a fixed number of places in the alphabet."},
  {m:4,t:"Substitution Cipher",d:"A cipher that replaces each unit of plaintext with another symbol."},
  {m:4,t:"Transposition Cipher",d:"A cipher that rearranges the order of characters without changing them."},
  {m:4,t:"Hashing",d:"Converting data into a fixed-length, irreversible value called a hash."},
  {m:4,t:"Salt",d:"Random data added to a password before hashing so identical passwords hash differently."},
  {m:4,t:"Steganography",d:"Hiding a message inside another file, such as an image, so its existence is concealed."},
  {m:4,t:"Frequency Analysis",d:"Breaking a cipher by studying how often letters or symbols appear."},
  {m:4,t:"Key Management",d:"The secure creation, distribution, storage, and retirement of cryptographic keys."},
  {m:5,t:"Social Engineering",d:"Using psychological tricks to manipulate people into revealing information or granting access."},
  {m:5,t:"Phishing",d:"A social engineering attack, usually by email, that tricks a target into giving up info or clicking a malicious link."},
  {m:5,t:"Spear Phishing",d:"A targeted phishing attack aimed at a specific person or organization."},
  {m:5,t:"Whaling",d:"A phishing attack that targets high-profile individuals like executives."},
  {m:5,t:"Vishing",d:"Social engineering carried out by voice phone call."},
  {m:5,t:"Smishing",d:"Phishing carried out through SMS text messages."},
  {m:5,t:"Pretexting",d:"Creating a believable fake reason to contact a target and gain their trust."},
  {m:5,t:"Baiting",d:"Luring a victim with the promise of a good, like a free download or a dropped USB drive."},
  {m:5,t:"Tailgating",d:"Following closely behind an authorized person into a restricted area without their knowledge."},
  {m:5,t:"Piggybacking",d:"Getting an authorized person to knowingly grant you access to a restricted area."},
  {m:5,t:"Shoulder Surfing",d:"Watching a user enter sensitive information so it can be used later."},
  {m:5,t:"Dumpster Diving",d:"Searching a target's physical trash for information useful to an attack."},
  {m:5,t:"Impersonation",d:"Pretending to be someone else to gain trust or access."},
  {m:5,t:"Quid Pro Quo",d:"Offering a service or benefit in exchange for information or access."},
  {m:5,t:"OSINT",d:"Open Source Intelligence — information gathered from publicly available sources."},
  {m:5,t:"Human Vulnerabilities",d:"Traits like trust, fear, curiosity, or helpfulness that attackers exploit in social engineering."},
  {m:5,t:"Social Engineering Tactics",d:"The specific techniques attackers use, such as phishing, pretexting, baiting, and tailgating."},
  {m:5,t:"Prevention and Mitigation",d:"Training, policies, and controls used to reduce the risk of social engineering attacks."},
  {m:6,t:"Linux",d:"A free, open-source operating system based on the Unix design."},
  {m:6,t:"Kernel",d:"The core of an operating system that manages hardware and system resources."},
  {m:6,t:"Shell",d:"A program that interprets and runs the commands a user types."},
  {m:6,t:"Bash",d:"A common Linux shell and command language."},
  {m:6,t:"Terminal",d:"A text interface used to enter commands."},
  {m:6,t:"Command Line Interface (CLI)",d:"Controlling a computer by typing text commands rather than clicking."},
  {m:6,t:"Distribution (Distro)",d:"A packaged version of Linux, such as Ubuntu, Debian, or Kali."},
  {m:6,t:"Root",d:"The all-powerful administrator account on a Linux system."},
  {m:6,t:"Home Directory",d:"The personal folder assigned to a user account."},
  {m:6,t:"File System",d:"The way an operating system organizes and stores files."},
  {m:6,t:"Absolute Path",d:"A file location written from the root of the file system (starting with a slash)."},
  {m:6,t:"Relative Path",d:"A file location written from the current directory."},
  {m:6,t:"Permissions",d:"Settings that control who can read, write, or execute a file."},
  {m:6,t:"sudo",d:"A command that runs a task with superuser (administrator) privileges."},
  {m:6,t:"Package Manager",d:"A tool that installs, updates, and removes software."},
  {m:6,t:"Open Source",d:"Software whose source code is freely available to view and modify."},
  {m:6,t:"Man Page",d:"Built-in Linux documentation for a command, shown with the man command."},
  {m:6,t:"User and Group Management",d:"Creating and controlling user accounts and groups along with their permissions."},
  {m:6,t:"Network Configuration",d:"Setting up a system's network interfaces, IP addresses, and connectivity."},
  {m:7,t:"User Account",d:"An identity that gives a person access to a system with specific permissions."},
  {m:7,t:"Group",d:"A collection of user accounts managed together for permissions."},
  {m:7,t:"File Permissions (rwx)",d:"Read, write, and execute settings applied to owner, group, and others."},
  {m:7,t:"Octal Permissions",d:"Representing file permissions as numbers, such as 755 or 644."},
  {m:7,t:"Process",d:"A running instance of a program."},
  {m:7,t:"Daemon",d:"A background process that provides a service on a system."},
  {m:7,t:"Cron",d:"A Linux scheduler that runs tasks automatically at set times."},
  {m:7,t:"Log File",d:"A record of system or application events, useful for troubleshooting and security."},
  {m:7,t:"Repository",d:"A storage location from which software packages are downloaded."},
  {m:7,t:"apt",d:"A package manager used on Debian and Ubuntu Linux."},
  {m:7,t:"Partition",d:"A section of a storage drive treated as a separate unit."},
  {m:7,t:"SSH",d:"Secure Shell — an encrypted protocol for remotely accessing a computer."},
  {m:7,t:"Pipe",d:"A feature that sends the output of one command as input to another."},
  {m:7,t:"Redirection",d:"Sending command output to (or input from) a file instead of the screen."},
  {m:7,t:"grep",d:"A command that searches text for lines matching a pattern."},
  {m:7,t:"chmod",d:"A command that changes a file's permissions."},
  {m:7,t:"chown",d:"A command that changes a file's owner."},
  {m:7,t:"Process Management",d:"Monitoring and controlling the programs currently running on a system."},
  {m:7,t:"Logging",d:"Recording system and application events for monitoring and troubleshooting."},
  {m:7,t:"Shell Scripting",d:"Writing scripts of shell commands to automate repetitive tasks."},
  {m:8,t:"Windows",d:"A widely used operating system developed by Microsoft."},
  {m:8,t:"Registry",d:"A hierarchical database that stores Windows configuration settings."},
  {m:8,t:"Active Directory",d:"A Microsoft service that manages users, computers, and permissions on a network."},
  {m:8,t:"Domain",d:"A group of networked computers managed centrally, often by Active Directory."},
  {m:8,t:"Group Policy",d:"A Windows feature for centrally managing settings and security across many computers."},
  {m:8,t:"PowerShell",d:"A powerful command-line shell and scripting language for Windows."},
  {m:8,t:"Command Prompt (cmd)",d:"The classic Windows text command interpreter."},
  {m:8,t:"NTFS",d:"The default Windows file system, which supports permissions and encryption."},
  {m:8,t:"Task Manager",d:"A tool that shows running processes and system performance."},
  {m:8,t:"Event Viewer",d:"A tool that displays logs of system, security, and application events."},
  {m:8,t:"User Account Control (UAC)",d:"A Windows feature that asks for approval before changes that need admin rights."},
  {m:8,t:"Service",d:"A program that runs in the background to support the OS or applications."},
  {m:8,t:"Scheduled Task",d:"A job Windows runs automatically at a set time or trigger."},
  {m:8,t:"Windows Defender",d:"Microsoft's built-in anti-malware protection."},
  {m:8,t:"BitLocker",d:"A Windows feature that encrypts entire drives."},
  {m:8,t:"Local Account",d:"An account that exists only on a single computer, not on a domain."},
  {m:8,t:"Patch",d:"A software update that fixes bugs or security vulnerabilities."},
  {m:8,t:"File and Folder Permissions",d:"Settings that control which users can read, change, or run files and folders."},
  {m:8,t:"Disk Management",d:"The Windows tool for creating, formatting, and managing drive partitions."},
  {m:8,t:"Remote Management",d:"Administering a computer from another location, for example via Remote Desktop."},
  {m:8,t:"Event Logs",d:"Records of system, security, and application events kept by Windows."},
  {m:8,t:"Patch Management",d:"The process of testing and applying software updates to fix vulnerabilities."},
  {m:9,t:"Capture the Flag (CTF)",d:"A cybersecurity competition where players solve challenges to find hidden flags."},
  {m:9,t:"National Cyber League (NCL)",d:"A national CTF competition for students to practice real cybersecurity skills."},
  {m:9,t:"Flag",d:"A secret string players must find to prove they solved a challenge."},
  {m:9,t:"Cyber Range",d:"A safe, simulated environment for practicing cybersecurity skills."},
  {m:9,t:"NCL Gym",d:"The NCL practice environment where players train before the games."},
  {m:9,t:"Enumeration",d:"Systematically discovering usernames, hosts, and services on a target."},
  {m:9,t:"Password Cracking",d:"Recovering passwords from stored or captured data, often using tools."},
  {m:9,t:"Wireshark",d:"A tool that captures and analyzes network traffic."},
  {m:9,t:"Forensics",d:"Investigating digital evidence to reconstruct what happened."},
  {m:9,t:"Log Analysis",d:"Examining log files to find useful or suspicious activity."},
  {m:9,t:"Web Exploitation",d:"Finding and abusing weaknesses in websites and web applications."},
  {m:9,t:"Scanning",d:"Probing a system or network to discover open ports and services."},
  {m:9,t:"Writeup",d:"A written explanation of how a challenge was solved."},
  {m:9,t:"Network Security",d:"Protecting networks and the data on them from intrusion, misuse, or attack."},
  {m:9,t:"Penetration Testing",d:"Authorized simulated attacks used to find and fix security weaknesses."},
  {m:9,t:"Incident Response",d:"The organized process of detecting, containing, and recovering from a cyberattack."},
  {m:9,t:"Cyber Threat Intelligence",d:"Collected information about attackers and threats used to improve defenses."},
  {m:10,t:"Network",d:"Two or more connected devices that can share data."},
  {m:10,t:"LAN",d:"Local Area Network — a network covering a small area like a home or school."},
  {m:10,t:"WAN",d:"Wide Area Network — a network that spans large distances, like the Internet."},
  {m:10,t:"IP Address",d:"A unique number that identifies a device on a network."},
  {m:10,t:"IPv4",d:"The 32-bit Internet addressing scheme, written as four numbers (e.g., 192.168.1.1)."},
  {m:10,t:"IPv6",d:"The newer 128-bit Internet addressing scheme that allows far more addresses."},
  {m:10,t:"MAC Address",d:"A hardware address permanently assigned to a network interface."},
  {m:10,t:"Subnet",d:"A logical subdivision of a larger network."},
  {m:10,t:"Router",d:"A device that forwards data between different networks."},
  {m:10,t:"Switch",d:"A device that connects devices within one network and forwards data by MAC address."},
  {m:10,t:"Packet",d:"A small chunk of data sent across a network."},
  {m:10,t:"Protocol",d:"A set of rules that governs how devices communicate."},
  {m:10,t:"TCP",d:"Transmission Control Protocol — provides reliable, ordered delivery of data."},
  {m:10,t:"UDP",d:"User Datagram Protocol — provides fast, connectionless delivery without guaranteed order."},
  {m:10,t:"DNS",d:"Domain Name System — translates domain names into IP addresses."},
  {m:10,t:"DHCP",d:"A protocol that automatically assigns IP addresses to devices."},
  {m:10,t:"Port",d:"A numbered endpoint that identifies a specific service on a device."},
  {m:10,t:"Firewall",d:"Hardware or software that allows or blocks network traffic based on rules."},
  {m:10,t:"HTTPS",d:"HTTP secured with encryption (TLS) to protect web traffic."},
  {m:10,t:"OSI Model",d:"A seven-layer model that describes how data moves through a network."},
  {m:10,t:"VPN",d:"Virtual Private Network — an encrypted tunnel that protects traffic over a public network."},
  {m:10,t:"Network Topology",d:"The physical or logical arrangement of devices in a network, such as star, bus, or mesh."},
  {m:10,t:"TCP/IP",d:"The core suite of protocols that powers Internet communication."},
  {m:10,t:"Network Devices",d:"Hardware such as routers, switches, and access points that build and run networks."},
  {m:10,t:"Wireless Networking",d:"Connecting devices to a network using radio signals instead of cables."},
  {m:10,t:"Network Performance",d:"How well a network moves data, measured by speed, latency, and reliability."},
  {m:11,t:"Malware",d:"Malicious software that damages a device or gives an attacker access to it."},
  {m:11,t:"Virus",d:"Malware that must be activated by a user opening or running a file."},
  {m:11,t:"Worm",d:"Malware that spreads from computer to computer without human interaction."},
  {m:11,t:"Trojan",d:"Malware hidden inside software that appears harmless."},
  {m:11,t:"Ransomware",d:"Malware that encrypts files and demands payment for the decryption key."},
  {m:11,t:"Spyware",d:"Malware that secretly tracks a user's actions and reports back to an attacker."},
  {m:11,t:"Rootkit",d:"Malware that controls the operating system and hides itself from detection."},
  {m:11,t:"Keylogger",d:"Software or hardware that records a user's keystrokes."},
  {m:11,t:"Botnet",d:"A network of infected computers controlled by an attacker."},
  {m:11,t:"Zero-Day",d:"A vulnerability with no patch available yet."},
  {m:11,t:"Payload",d:"The part of malware that performs the malicious action."},
  {m:11,t:"Backdoor",d:"A hidden way to bypass normal authentication and access a system."},
  {m:11,t:"Privilege Escalation",d:"Gaining a higher level of access than authorized."},
  {m:11,t:"Buffer Overflow",d:"Feeding more data into memory than allotted, which can crash a system or run malicious code."},
  {m:11,t:"Cyber Kill Chain",d:"A model describing the stages of a cyberattack, from reconnaissance to actions on objectives."},
  {m:11,t:"Reconnaissance",d:"The first attack phase — gathering information about a target."},
  {m:11,t:"Weaponization",d:"Creating a deliverable malicious payload."},
  {m:11,t:"Command and Control (C2)",d:"The channel an attacker uses to remotely control compromised systems."},
  {m:11,t:"Exfiltration",d:"Stealing and transferring data out of a target's network."},
  {m:11,t:"Indicators of Compromise (IoC)",d:"Evidence in logs or systems that a breach has occurred."},
  {m:11,t:"Malware Techniques",d:"Methods malware uses to infect, hide, spread, or persist on a system."},
  {m:11,t:"Vulnerability Types",d:"Categories of weaknesses, such as software, configuration, or human vulnerabilities."},
  {m:11,t:"Vulnerability Assessment",d:"Systematically identifying and evaluating security weaknesses in a system."},
  {m:11,t:"Vulnerability Scanning",d:"Using automated tools to detect known vulnerabilities in systems."},
  {m:11,t:"Vulnerability Management",d:"The ongoing process of finding, prioritizing, and fixing vulnerabilities."},
  {m:11,t:"Threat Actor",d:"An individual or group responsible for carrying out a cyberattack."},
  {m:12,t:"Database",d:"An organized collection of data stored electronically."},
  {m:12,t:"Relational Database",d:"A database that stores data in related tables of rows and columns."},
  {m:12,t:"Table",d:"A set of data organized into rows and columns."},
  {m:12,t:"Record (Row)",d:"A single entry in a table."},
  {m:12,t:"Field (Column)",d:"A single attribute stored for every record in a table."},
  {m:12,t:"Primary Key",d:"A field that uniquely identifies each record in a table."},
  {m:12,t:"Foreign Key",d:"A field that links one table to the primary key of another."},
  {m:12,t:"Query",d:"A request to retrieve or modify data in a database."},
  {m:12,t:"SQL",d:"Structured Query Language — the standard language for working with relational databases."},
  {m:12,t:"SELECT",d:"The SQL command that retrieves data from a database."},
  {m:12,t:"INSERT",d:"The SQL command that adds new records to a table."},
  {m:12,t:"UPDATE",d:"The SQL command that changes existing records."},
  {m:12,t:"DELETE",d:"The SQL command that removes records."},
  {m:12,t:"WHERE",d:"A SQL clause that filters which records a command affects."},
  {m:12,t:"JOIN",d:"A SQL operation that combines rows from two or more tables."},
  {m:12,t:"Schema",d:"The structure that defines a database's tables, fields, and relationships."},
  {m:12,t:"DBMS",d:"Database Management System — software used to create and manage databases."},
  {m:12,t:"SQL Injection",d:"An attack that inserts malicious SQL into an input to manipulate a database."},
  {m:12,t:"Input Sanitization",d:"Cleaning user input to prevent attacks like SQL injection."},
  {m:12,t:"Data Types",d:"Categories of values a database column can store, such as text, number, or date."},
  {m:12,t:"Operators",d:"Symbols used in queries to compare or combine values, such as =, >, AND, and OR."},
  {m:12,t:"Stored Procedure",d:"A saved set of SQL statements that can be run as a single command."},
  {m:13,t:"Communication Skills",d:"Clearly sharing information in writing and speech with technical and non-technical people."},
  {m:13,t:"Problem-Solving Skills",d:"Breaking down challenges and finding effective, logical solutions."},
  {m:13,t:"Teamwork",d:"Working well with others to reach a shared goal."},
  {m:13,t:"Adaptability",d:"Adjusting quickly to new tools, situations, and challenges."},
  {m:13,t:"Attention to Detail",d:"Noticing small but important information that others might miss."},
  {m:13,t:"Leadership",d:"Guiding, motivating, and supporting a team toward a goal."},
  {m:13,t:"Customer Service",d:"Helping and supporting users professionally and patiently."}
];
  return { modules: MODULES, terms: VOCAB };
})();
