// © 2026 Robert Reasey, South Fayette School District. Licensed CC BY-NC 4.0 (attribution required, no commercial use). See LICENSE.md.
/* Shared vocab pool for apcsp — consumed by ctf.html (window.CTF_VOCAB).
   Mirror of the VOCAB array in apcsp/vocab.html. m = classroom module. */
window.APCSP_VOCAB = { terms: [
  {m:1,t:"Problem",d:"A general description of a task that can (or cannot) be solved with an algorithm."},
  {m:1,t:"Algorithm",d:"A finite set of instructions that accomplish a specific task. Every algorithm can be constructed using combinations of sequencing, selection, and iteration."},
  {m:1,t:"Sequencing",d:"Putting the steps of an algorithm in order."},
  {m:1,t:"Selection",d:"Determines which parts of an algorithm are executed based on a condition being true or false. The use of try / exception statements is a form of selection."},
  {m:1,t:"Iteration",d:"A repetitive portion of an algorithm. Iteration repeats until a given condition is met or for a specified number of times. The use of recursion is a form of iteration."},
  {m:1,t:"Efficiency",d:"A measure of how many steps are needed to complete an algorithm."},
  {m:1,t:"Linear Search",d:"A search that checks each element of a list in order until the value is found or the list ends."},
  {m:1,t:"Binary Search",d:"A search that starts in the middle of a sorted list and removes half the data each step until the value is found."},
  {m:1,t:"Reasonable Time",d:"Algorithms with polynomial efficiency or lower (constant, linear, square, cube) run in a reasonable amount of time."},
  {m:1,t:"Unreasonable Time",d:"Algorithms with exponential or factorial efficiency run in an unreasonable amount of time."},
  {m:1,t:"Heuristic",d:"An approach that gives a 'good enough' solution when a perfect one is impractical or impossible."},
  {m:1,t:"Decision Problem",d:"A problem with a yes/no answer (e.g., is there a path from A to B?)."},
  {m:1,t:"Optimization Problem",d:"A problem seeking the best solution among many (e.g., the shortest path from A to B)."},
  {m:1,t:"Undecidable Problem",d:"A problem for which no algorithm can always give a correct yes-or-no answer."},
  {m:1,t:"Sequential Computing",d:"A model in which a program runs in order, one command at a time."},
  {m:1,t:"Parallel Computing",d:"A model in which a program is broken into pieces, some of which run at the same time."},
  {m:1,t:"Distributed Computing",d:"A model in which a program runs across multiple devices."},
  {m:1,t:"Speedup",d:"The time to complete a task sequentially divided by the time to complete it in parallel."},
  {m:2,t:"Program",d:"A collection of program statements that run one command at a time."},
  {m:2,t:"Program Statement",d:"A single command or instruction; also called a code statement."},
  {m:2,t:"Sequential Programming",d:"Program statements run in order, from top to bottom."},
  {m:2,t:"Event-Driven Programming",d:"Some statements run only when triggered by an event, like a click or key press."},
  {m:2,t:"Event",d:"An action that supplies input to a program, such as a key press, mouse click, or program start."},
  {m:2,t:"User Interface",d:"The inputs and outputs that let a user interact with software (buttons, menus, text, graphics)."},
  {m:2,t:"Input",d:"Data sent to a program for processing — tactile, audio, visual, or text."},
  {m:2,t:"Output",d:"Data sent from a program to a device — tactile, audio, visual, or text."},
  {m:2,t:"Variable",d:"A named reference to a value that can be used repeatedly in a program."},
  {m:2,t:"Assignment Operator",d:"Lets a program change the value stored in a variable."},
  {m:2,t:"String",d:"An ordered sequence of characters."},
  {m:2,t:"Expression",d:"A combination of operators and values that evaluates to a single value."},
  {m:2,t:"Boolean Value",d:"A value that is either true or false."},
  {m:2,t:"Comparison Operators",d:"Operators (<, >, <=, >=, ==, !=) that create a Boolean expression."},
  {m:2,t:"Logical Operator",d:"NOT, AND, and OR, which evaluate to a Boolean value."},
  {m:2,t:"Conditional Statement",d:"Runs different code based on the value of a Boolean expression."},
  {m:2,t:"Function",d:"A named group of programming instructions; also called a procedure."},
  {m:2,t:"Function Call",d:"A command that executes the code inside a function."},
  {m:2,t:"List",d:"An ordered collection of elements."},
  {m:2,t:"Element",d:"An individual value in a list, assigned a unique index."},
  {m:2,t:"Index",d:"A number used to reference an element in a list or string."},
  {m:2,t:"Infinite Loop",d:"A loop whose ending condition never becomes true, so it never stops."},
  {m:2,t:"Traversal",d:"The process of accessing each item in a list one at a time."},
  {m:2,t:"Parameter",d:"An input variable of a procedure. Explicit parameters are defined in the procedure header; implicit parameters are assigned in anticipation of a call to the procedure, such as through interaction with a user interface."},
  {m:2,t:"Argument",d:"The value of a parameter when a procedure is called."},
  {m:2,t:"Return",d:"Sends control (and a value) back to where the function was called."},
  {m:2,t:"Procedural Abstraction",d:"Using a procedure by knowing what it does, not how it does it."},
  {m:2,t:"Data Abstraction",d:"Giving a collection of data a name without specifying representation details."},
  {m:2,t:"Library",d:"A group of functions (procedures) used to create new programs."},
  {m:2,t:"API",d:"Application Program Interface — specifications for how a library's functions behave and are used."},
  {m:2,t:"Debugging",d:"Finding and fixing problems in an algorithm or program."},
  {m:3,t:"Binary",d:"A way of representing information using only two options."},
  {m:3,t:"Bit",d:"The single unit of information in a computer, a 0 or 1 (short for 'binary digit')."},
  {m:3,t:"Byte",d:"A group of 8 bits."},
  {m:3,t:"Overflow Error",d:"An error from trying to represent a number that is too large."},
  {m:3,t:"Round-off Error",d:"An error from trying to represent a number too precisely, so the value is rounded."},
  {m:3,t:"Analog Data",d:"Data whose values change continuously over time, like sound, color, or a runner's position."},
  {m:3,t:"Digital Data",d:"Data that changes discretely through a finite set of possible values."},
  {m:3,t:"Sampling",d:"Creating a digital version of analog data by measuring it at regular intervals called samples."},
  {m:3,t:"Lossless Compression",d:"Reducing the bits needed to store data without losing any information; the process is reversible."},
  {m:3,t:"Lossy Compression",d:"Reducing the bits needed by discarding some information; the process is not reversible."},
  {m:4,t:"Citizen Science",d:"Scientific research done partly by distributed volunteers who contribute data using their own devices."},
  {m:4,t:"Cleaning Data",d:"Making data uniform without changing its meaning, e.g. standardizing spellings and abbreviations."},
  {m:4,t:"Correlation",d:"A relationship between two pieces of data, where one varies in relation to the other."},
  {m:4,t:"Crowdsourcing",d:"Getting input or information from a large number of people via the Internet."},
  {m:4,t:"Information",d:"The collection of facts and patterns extracted from data."},
  {m:4,t:"Data Bias",d:"Data that does not accurately reflect the full population or phenomenon being studied."},
  {m:4,t:"Data Filtering",d:"Choosing a smaller subset of a data set to use for analysis."},
  {m:5,t:"Intellectual Property",d:"A creative work or invention to which its creator has rights, such as a copyright, patent, or trademark."},
  {m:5,t:"Creative Commons",d:"Public copyright licenses that let creators allow others to share, use, and build on their work."},
  {m:5,t:"Documentation",d:"A written description of how a command or piece of code works or was developed."},
  {m:5,t:"Comment",d:"Program documentation written in the code for people to read; it does not affect how the program runs."},
  {m:5,t:"Pair Programming",d:"A collaborative style where two programmers switch between writing code and planning."},
  {m:5,t:"Development Process",d:"The phases used to create software — investigating, designing, prototyping, and testing."},
  {m:6,t:"Computing Device",d:"A machine that can run a program — computer, tablet, server, router, or smart sensor."},
  {m:6,t:"Computing System",d:"A group of computing devices and programs working together for a common purpose."},
  {m:6,t:"Computing Network",d:"A group of interconnected computing devices capable of sending or receiving data."},
  {m:6,t:"Path",d:"The series of connections between a sender and a receiver on a network."},
  {m:6,t:"Bandwidth",d:"The maximum amount of data that can be sent in a fixed time, measured in bits per second."},
  {m:6,t:"Protocol",d:"An agreed-upon set of rules that specify the behavior of a system."},
  {m:6,t:"IP Address",d:"The unique number assigned to each device on the Internet."},
  {m:6,t:"Internet Protocol (IP)",d:"The protocol that assigns unique addresses and sends data across the Internet."},
  {m:6,t:"Router",d:"A type of computer that forwards data across a network."},
  {m:6,t:"Packet",d:"A chunk of data sent over a network; large messages are divided into packets."},
  {m:6,t:"Redundancy",d:"Including extra components so a system keeps working even if individual parts fail."},
  {m:6,t:"Fault Tolerant",d:"Able to keep functioning even when individual components fail."},
  {m:6,t:"HTTP",d:"HyperText Transfer Protocol — used for transmitting web pages over the Internet."},
  {m:6,t:"Internet",d:"A network of interconnected networks that use standardized, open communication protocols."},
  {m:6,t:"World Wide Web",d:"A system of linked pages, programs, and files."},
  {m:6,t:"Digital Divide",d:"Differing access to computing devices and the Internet based on socioeconomic, geographic, or demographic factors."},
  {m:6,t:"Computing Innovation",d:"An innovation that includes a program as an integral part of its function."},
  {m:6,t:"Personally Identifiable Information (PII)",d:"Information about an individual that identifies, links, relates to, or describes them."},
  {m:6,t:"Phishing",d:"A technique that tricks a user into providing personal information used to access sensitive resources."},
  {m:6,t:"Keylogging",d:"Recording every keystroke a user makes to gain access to passwords and confidential information."},
  {m:6,t:"Malware",d:"Software intended to damage a computing system or take partial control of its operation."},
  {m:6,t:"Rogue Access Point",d:"A wireless access point that gives unauthorized access to a secure network."},
  {m:6,t:"Encryption",d:"Encoding a message so that only authorized parties can read it."},
  {m:6,t:"Decryption",d:"Reversing encryption to reproduce the original plain text."},
  {m:6,t:"Symmetric Key Encryption",d:"Encryption that uses one key for both encryption and decryption."},
  {m:6,t:"Public Key Encryption",d:"Uses a public key to encrypt and a private key to decrypt; only the private key can decrypt the message."},
  {m:6,t:"Multi-factor Authentication",d:"Requiring at least two steps to unlock protected information, each adding a layer of security."},
  {m:1,t:"Abstraction",d:"Reducing complexity by focusing on the main idea and hiding unnecessary detail."},
  {m:1,t:"Scalability",d:"The ability of a system or solution to handle growth in data, users, or work."},
  {m:1,t:"Instance of a Problem",d:"A specific case of a general problem with particular input values."},
  {m:1,t:"Decidable Problem",d:"A decision problem for which an algorithm can always give a correct yes-or-no answer."},
  {m:1,t:"Algorithmic Bias",d:"Unfair outcomes produced by an algorithm, often reflecting bias in its data or design."},
  {m:2,t:"Programming Language",d:"A formal language used to write instructions that a computer can run."},
  {m:2,t:"Logic Error",d:"A mistake that lets a program run but produce incorrect results."},
  {m:2,t:"Syntax Error",d:"A mistake that breaks the rules of the programming language, so the code will not run."},
  {m:2,t:"Runtime Error",d:"An error that occurs while a program is running, causing it to crash or stop."},
  {m:2,t:"Substring",d:"A contiguous part of a string."},
  {m:2,t:"String Concatenation",d:"Joining two or more strings end to end to form one string."},
  {m:2,t:"Modularity",d:"Breaking a program into separate, reusable pieces such as functions."},
  {m:2,t:"Modulus Operator",d:"An operator that returns the remainder of a division."},
  {m:3,t:"Number Bases",d:"Systems for representing numbers using a fixed base, such as base-2 (binary) or base-10 (decimal)."},
  {m:4,t:"Simulation",d:"A model that imitates a real-world process to study or predict its behavior."},
  {m:5,t:"Open Source",d:"Software whose source code is freely available to view, use, and modify."},
  {m:5,t:"Open Access",d:"Making research or content freely available online without payment or most restrictions."},
  {m:6,t:"Strong Password",d:"A long, complex password that is hard to guess or crack."},
  {m:6,t:"Metadata",d:"Data that describes other data, such as a photo's date, size, or location."},
  {m:6,t:"Routing",d:"The process of choosing the path that data takes across a network."},
  {m:6,t:"Data Streams",d:"Data broken into packets and sent in sequence across a network."},
  {m:6,t:"Computer Virus",d:"Malware that attaches to a file and spreads when that file is run."},
  {m:3,t:"Central Processing Unit (CPU)",d:"The component of a computer that carries out the instructions of a program by performing calculations and decision-making."},
  {m:3,t:"Integer",d:"A whole number — positive, negative, or zero — with no fractional or decimal part."},
  {m:3,t:"Floating Point Number",d:"A number represented with a decimal point, used to approximate real numbers that include fractional values."},
  {m:3,t:"Logic Gate",d:"A physical or idealized device that performs a Boolean operation on one or more binary inputs to produce a single binary output."},
  {m:3,t:"Moore's Law",d:"The observation that the number of transistors on a computer chip (and roughly its processing power) doubles about every two years."},
  {m:2,t:"Global Variable",d:"A variable defined outside of any procedure, accessible from anywhere in the program."},
  {m:2,t:"Local Variable",d:"A variable defined inside a procedure, accessible only within that procedure."},
  {m:4,t:"Data Mining",d:"Analyzing large data sets to find patterns, anomalies, and correlations that can be used to predict outcomes."},
  {m:6,t:"Firewall",d:"A network security system that monitors and controls incoming and outgoing traffic based on a set of rules."},
  {m:6,t:"Denial of Service Attack (DoS/DDoS)",d:"An attack that floods a server or network with traffic to overwhelm it and deny service to legitimate users; a distributed denial of service attack (DDoS) launches the flood from many devices at once."},
  {m:6,t:"Digital Certificate",d:"An electronic document, issued by a trusted certificate authority, that verifies the identity of a website or sender and enables secure encrypted communication."},
  {m:5,t:"Procedure",d:"A named group of programming instructions that may have parameters and return values. Procedures are referred to by different names, such as method, function, or constructor, depending on the programming language."},
  {m:5,t:"Purpose",d:"The problem being solved or creative interest being pursued through the program."},
  {m:5,t:"Program Functionality",d:"The behavior of a program during execution, often described by how a user interacts with it."},
  {m:5,t:"Program Code Segment",d:"A collection of program statements that are part of a program. For text-based code, the segment should be continuous and within the same procedure; for block-based code, contained in the same starter (\u201cHat\u201d) block."},
  {m:5,t:"Collection Type",d:"Aggregates elements in a single structure. Examples include databases, hash tables, dictionaries, sets, or any other type that aggregates elements in a single structure."},
  {m:5,t:"Data Stored in a List",d:"Input into a list can come through an initialization or through computation on other variables or list elements."},
  {m:5,t:"List Being Used",d:"A list is being used when a program creates new data from existing data or accesses multiple elements in the list."},
  {m:5,t:"Student-Developed Procedure / Algorithm",d:"Program code that has been written (individually or collaboratively) by the student who submitted the response. Calls to existing program code or libraries can be included but are not considered student developed; built-in event handlers are also not considered student developed."}
] };
