/* Shared vocab pool for web3 — consumed by ctf.html (window.CTF_VOCAB).
   Mirror of the VOCAB array in web3/vocab.html. m = classroom module. */
window.WEB3_VOCAB = { terms: [
  {m:1,t:"Blockchain",d:"A shared, append-only digital ledger of transactions maintained across many computers, where records are grouped into linked blocks."},
  {m:1,t:"Consensus",d:"Agreement among network participants on which transactions are valid and get added to the blockchain."},
  {m:1,t:"Cryptocurrency",d:"A digital currency secured by cryptography and recorded on a blockchain, not issued by any government."},
  {m:1,t:"DAO (Decentralized Autonomous Organization)",d:"An organization governed by its members through smart contracts and token votes, with no central boss."},
  {m:1,t:"DApp (Decentralized Application)",d:"An app whose backend runs on a blockchain via smart contracts instead of a central server."},
  {m:1,t:"Decentralization",d:"Distributing control and decision-making across a network instead of a single central authority."},
  {m:1,t:"DeFi (Decentralized Finance)",d:"Financial services — lending, trading, saving — built on blockchains without traditional banks."},
  {m:1,t:"Digital Wallet",d:"Software or hardware that stores your keys and lets you send, receive, and manage crypto assets."},
  {m:1,t:"Distributed Ledger",d:"A database shared, replicated, and synchronized across many participants rather than stored in one place."},
  {m:1,t:"Governance",d:"The process and rules by which a blockchain project or DAO makes decisions."},
  {m:1,t:"Interoperability",d:"The ability of different blockchains to share data and value with one another."},
  {m:1,t:"IPFS (InterPlanetary File System)",d:"A peer-to-peer system for storing and sharing files across a distributed network, often used to host NFT data."},
  {m:1,t:"Mining",d:"Using computing power to validate transactions and add new blocks, earning rewards in return."},
  {m:1,t:"Oracles",d:"Services that feed real-world data into a blockchain so smart contracts can use it."},
  {m:1,t:"Privacy-Preserving",d:"Designed to protect users' personal data and keep transactions confidential."},
  {m:1,t:"Proof of Work",d:"A consensus mechanism where miners compete to solve a hard math puzzle to add the next block."},
  {m:1,t:"Proof of Stake",d:"A consensus mechanism where validators are chosen to add blocks based on the crypto they lock up."},
  {m:1,t:"Scalability",d:"A network's ability to handle more transactions as usage grows."},
  {m:1,t:"Smart Contract",d:"Self-executing code stored on a blockchain that runs automatically when its conditions are met."},
  {m:1,t:"Token",d:"A digital asset created on top of an existing blockchain, usually via a smart contract."},
  {m:1,t:"Web 3.0",d:"A vision of a decentralized internet where users own their data, identity, and assets."},
  {m:1,t:"Web3 Browser",d:"A browser (or extension) that can connect to blockchains and interact with dApps."},
  {m:2,t:"Biometric Authentication",d:"Verifying identity with a fingerprint, face, or other body feature."},
  {m:2,t:"Cold Wallet",d:"A crypto wallet kept offline, such as a hardware device, for greater security."},
  {m:2,t:"Contactless Payment",d:"Paying by tapping a card or phone near a reader, no swipe or contact needed."},
  {m:2,t:"Cryptocurrency",d:"A digital currency secured by cryptography and recorded on a blockchain, not issued by any government."},
  {m:2,t:"Custodial Wallet",d:"A wallet where a third party (like an exchange) holds your private keys for you."},
  {m:2,t:"Digital Wallet",d:"Software or hardware that stores your keys and lets you send, receive, and manage crypto assets."},
  {m:2,t:"Hot Wallet",d:"A crypto wallet connected to the internet — convenient, but more exposed to attacks."},
  {m:2,t:"Mobile Payment",d:"Making payments using a smartphone app or digital wallet."},
  {m:2,t:"Noncustodial Wallet",d:"A wallet where only you hold the private keys — you have full control and responsibility."},
  {m:2,t:"Peer-to-Peer (P2P) Payment",d:"Sending money directly from one person to another with no bank in between."},
  {m:2,t:"Private Key",d:"A secret cryptographic key that proves ownership and authorizes transactions; never share it."},
  {m:2,t:"Mnemonic Phrase (Passcode)",d:"A list of words that can restore access to a wallet; anyone who has it controls the funds."},
  {m:2,t:"Public Key",d:"A shareable cryptographic key others use to send you funds or verify your signature."},
  {m:2,t:"Scam",d:"A fraudulent scheme designed to trick people out of their money or crypto."},
  {m:2,t:"Token Association",d:"Linking a specific token to your wallet so it can send, receive, or hold it."},
  {m:2,t:"Two-factor Authentication (2FA)",d:"A second verification step, like a code from your phone, added to a password for extra security."},
  {m:3,t:"Address",d:"A shortened, shareable identifier derived from a public key, used to receive funds."},
  {m:3,t:"Altcoin",d:"Any cryptocurrency other than Bitcoin."},
  {m:3,t:"Blockchain",d:"A shared, append-only digital ledger of transactions maintained across many computers, where records are grouped into linked blocks."},
  {m:3,t:"Circulation",d:"The amount of a cryptocurrency currently available and being traded in the market."},
  {m:3,t:"Cold Wallet",d:"A crypto wallet kept offline, such as a hardware device, for greater security."},
  {m:3,t:"Cryptocurrency (Coin)",d:"The native digital money of a blockchain, such as Bitcoin or Ether."},
  {m:3,t:"Digital Wallet",d:"Software or hardware that stores your keys and lets you send, receive, and manage crypto assets."},
  {m:3,t:"Decentralized Exchange",d:"A platform that lets users trade crypto directly with each other through smart contracts."},
  {m:3,t:"Ethereum",d:"A blockchain platform, launched in 2015, that runs smart contracts and decentralized applications."},
  {m:3,t:"Fungible",d:"Interchangeable — each unit has the same value as any other, like dollars or ETH."},
  {m:3,t:"ICO (Initial Coin Offering)",d:"A fundraising event where a new crypto project sells its tokens to early investors."},
  {m:3,t:"Market Cap",d:"The total value of a cryptocurrency — price multiplied by the number of coins in circulation."},
  {m:3,t:"Max Circulation",d:"The maximum number of coins that will ever exist for a cryptocurrency."},
  {m:3,t:"Mining",d:"Using computing power to validate transactions and add new blocks, earning rewards in return."},
  {m:3,t:"Private Key",d:"A secret cryptographic key that proves ownership and authorizes transactions; never share it."},
  {m:3,t:"Proof of Stake",d:"A consensus mechanism where validators are chosen to add blocks based on the crypto they lock up."},
  {m:3,t:"Proof of Work",d:"A consensus mechanism where miners compete to solve a hard math puzzle to add the next block."},
  {m:3,t:"Public Key",d:"A shareable cryptographic key others use to send you funds or verify your signature."},
  {m:3,t:"Smart Contract",d:"Self-executing code stored on a blockchain that runs automatically when its conditions are met."},
  {m:3,t:"Staking",d:"Locking up cryptocurrency to help secure a network and earn rewards."},
  {m:3,t:"Supply",d:"The total amount of a token that exists."},
  {m:3,t:"Token",d:"A digital asset created on top of an existing blockchain, usually via a smart contract."},
  {m:3,t:"Tokenomics",d:"The design of a token's supply, distribution, and incentives."},
  {m:3,t:"Utility Token",d:"A token that gives holders access to a product or service on a platform."},
  {m:4,t:"Blockchain",d:"A shared, append-only digital ledger of transactions maintained across many computers, where records are grouped into linked blocks."},
  {m:4,t:"Collectibles",d:"Unique or limited digital items people collect, often as NFTs."},
  {m:4,t:"Copyright",d:"The legal right to control how an original creative work is copied and used."},
  {m:4,t:"Cryptocurrency",d:"A digital currency secured by cryptography and recorded on a blockchain, not issued by any government."},
  {m:4,t:"Decentralization",d:"Distributing control and decision-making across a network instead of a single central authority."},
  {m:4,t:"Digital Art",d:"Artwork created or presented in digital form, often sold as NFTs."},
  {m:4,t:"Digital Asset",d:"Anything of value that exists in digital form, such as crypto, tokens, or NFTs."},
  {m:4,t:"Gas Fees",d:"Fees paid to process transactions or run smart contracts on a blockchain."},
  {m:4,t:"Ethereum",d:"A blockchain platform, launched in 2015, that runs smart contracts and decentralized applications."},
  {m:4,t:"Inscription",d:"Data (like an image or text) written permanently onto a blockchain."},
  {m:4,t:"Intellectual Property (IP)",d:"Creations of the mind — art, music, inventions — that can be legally owned."},
  {m:4,t:"IPFS (InterPlanetary File System)",d:"A peer-to-peer system for storing and sharing files across a distributed network, often used to host NFT data."},
  {m:4,t:"Marketplace",d:"An online platform where NFTs or digital assets are bought and sold."},
  {m:4,t:"Metadata",d:"Descriptive information about an NFT, such as its name, traits, and linked media."},
  {m:4,t:"Minting",d:"Creating a new NFT or token and recording it on the blockchain."},
  {m:4,t:"Non-Fungible Token (NFT)",d:"A unique digital token that proves ownership of a specific item, such as art or a collectible."},
  {m:4,t:"Ownership Rights",d:"The rights a buyer receives when they own a digital asset or NFT."},
  {m:4,t:"Proof of Authenticity",d:"Verifiable proof that a digital item is genuine and not a copy."},
  {m:4,t:"Rarity",d:"How scarce an NFT's traits are compared to others in a collection."},
  {m:4,t:"Royalties",d:"Ongoing payments to a creator each time their NFT is resold."},
  {m:4,t:"Smart Contract",d:"Self-executing code stored on a blockchain that runs automatically when its conditions are met."},
  {m:4,t:"Tokenization",d:"Turning a real or digital asset into a token that can be traded on a blockchain."},
  {m:4,t:"Wallet",d:"Software or hardware that stores your keys and manages your crypto and NFTs."},
  {m:5,t:"Address",d:"A shortened, shareable identifier derived from a public key, used to receive funds."},
  {m:5,t:"Admin Key",d:"A special key that grants control over a token's settings or contract."},
  {m:5,t:"Decimals",d:"The number of decimal places a token can be divided into."},
  {m:5,t:"ERC-20",d:"A standard for creating fungible (interchangeable) tokens on Ethereum."},
  {m:5,t:"ERC-721",d:"A standard for creating non-fungible (unique) tokens on Ethereum."},
  {m:5,t:"Freeze Key",d:"A key that can pause or freeze transfers of a token."},
  {m:5,t:"Initial Supply",d:"The number of tokens created when a token is first launched."},
  {m:5,t:"Inscribe",d:"To write data permanently onto a blockchain."},
  {m:5,t:"IPFS (InterPlanetary File System)",d:"A peer-to-peer system for storing and sharing files across a distributed network, often used to host NFT data."},
  {m:5,t:"Private Key",d:"A secret cryptographic key that proves ownership and authorizes transactions; never share it."},
  {m:5,t:"Public Key Cryptography",d:"A security system using a paired public and private key to encrypt and verify data."},
  {m:5,t:"Royalties",d:"Ongoing payments to a creator each time their NFT is resold."},
  {m:5,t:"Supply",d:"The total amount of a token that exists."},
  {m:5,t:"Supply Key",d:"A key that controls whether more of a token can be minted or burned."},
  {m:5,t:"Tokenomics",d:"The design of a token's supply, distribution, and incentives."},
  {m:5,t:"Wallet Provider",d:"A company or app that offers a crypto wallet service."},
  {m:5,t:"Wipe Key",d:"A key that can remove a token from an account's balance."},
  {m:6,t:"Autonomous",d:"Operating on its own by code and rules, without ongoing human control."},
  {m:6,t:"Blockchain",d:"A shared, append-only digital ledger of transactions maintained across many computers, where records are grouped into linked blocks."},
  {m:6,t:"Consensus",d:"Agreement among network participants on which transactions are valid and get added to the blockchain."},
  {m:6,t:"DAO Treasury",d:"A shared pool of funds a DAO controls and spends through member votes."},
  {m:6,t:"Decentralized Governance Protocol",d:"The set of rules and smart contracts that let a community govern a project."},
  {m:6,t:"Decentralization",d:"Distributing control and decision-making across a network instead of a single central authority."},
  {m:6,t:"Fork",d:"A split in a blockchain into two paths, often from a rule change or disagreement."},
  {m:6,t:"Governance",d:"The process and rules by which a blockchain project or DAO makes decisions."},
  {m:6,t:"Liquid Democracy",d:"A voting system where members can vote directly or delegate their vote to someone they trust."},
  {m:6,t:"Meritocracy",d:"A system where influence is earned through contribution and proven ability."},
  {m:6,t:"Reputation",d:"A measure of how trusted or valuable a participant is in a community."},
  {m:6,t:"Reputation Mining",d:"Earning reputation or influence by contributing useful work to a network."},
  {m:6,t:"Smart Contract",d:"Self-executing code stored on a blockchain that runs automatically when its conditions are met."},
  {m:6,t:"Stakeholder",d:"Anyone with an interest or investment in a project's outcome."},
  {m:6,t:"Sybil Resistance",d:"A system's ability to stop one person from faking many identities to gain unfair power."},
  {m:6,t:"Token",d:"A digital asset created on top of an existing blockchain, usually via a smart contract."},
  {m:6,t:"Tokenomics",d:"The design of a token's supply, distribution, and incentives."},
  {m:6,t:"Transparency",d:"The property that transactions and decisions are open and visible to anyone."},
  {m:6,t:"Voting",d:"Casting a choice to help a community make a decision."},
  {m:6,t:"Whitepaper",d:"A document explaining a crypto project's purpose, technology, and plan."},
  {m:7,t:"Anonymity",d:"Being able to act without revealing your real identity."},
  {m:7,t:"Centralization",d:"Control concentrated in a single authority or organization."},
  {m:7,t:"Consensus Mechanism",d:"The method a blockchain uses to agree on valid transactions, such as PoW or PoS."},
  {m:7,t:"Data Privacy",d:"Protecting people's personal information from misuse or unwanted access."},
  {m:7,t:"Digital Identity",d:"The online representation of who a person is, which Web3 lets users own and control."},
  {m:7,t:"Intellectual Property (IP) Rights",d:"Legal rights that protect creators' original work."},
  {m:7,t:"Interoperability",d:"The ability of different blockchains to share data and value with one another."},
  {m:7,t:"Network Security",d:"Protecting a blockchain network from attacks and unauthorized access."},
  {m:7,t:"Regulatory Compliance",d:"Following the laws and rules that govern crypto and finance."},
  {m:7,t:"Smart Contract Auditing",d:"Reviewing smart contract code to find bugs and security flaws before launch."},
  {m:7,t:"Tokenomics",d:"The design of a token's supply, distribution, and incentives."},
  {m:7,t:"Transparency",d:"The property that transactions and decisions are open and visible to anyone."},
  {m:7,t:"User Consent and Control",d:"Giving users the power to decide how their data and assets are used."},
  {m:7,t:"Web3 Regulation",d:"Government rules and policies that apply to blockchain and crypto technologies."},
  {m:8,t:"Blockchain",d:"A shared, append-only digital ledger of transactions maintained across many computers, where records are grouped into linked blocks."},
  {m:8,t:"Consensus",d:"Agreement among network participants on which transactions are valid and get added to the blockchain."},
  {m:8,t:"Cryptocurrency",d:"A digital currency secured by cryptography and recorded on a blockchain, not issued by any government."},
  {m:8,t:"Decentralization",d:"Distributing control and decision-making across a network instead of a single central authority."},
  {m:8,t:"Distributed Ledger",d:"A database shared, replicated, and synchronized across many participants rather than stored in one place."},
  {m:8,t:"Ethereum",d:"A blockchain platform, launched in 2015, that runs smart contracts and decentralized applications."},
  {m:8,t:"Gas Fees",d:"Fees paid to process transactions or run smart contracts on a blockchain."},
  {m:8,t:"Immutable",d:"Unable to be changed once recorded on a blockchain."},
  {m:8,t:"Interoperability",d:"The ability of different blockchains to share data and value with one another."},
  {m:8,t:"Smart Contract",d:"Self-executing code stored on a blockchain that runs automatically when its conditions are met."},
  {m:8,t:"Token",d:"A digital asset created on top of an existing blockchain, usually via a smart contract."},
  {m:8,t:"Trustlessness",d:"A system where participants can transact without trusting each other or a middleman."},
  {m:8,t:"User Interface (UI)",d:"The screens, buttons, and visuals people use to interact with an app."},
  {m:8,t:"Wallet",d:"Software or hardware that stores your keys and manages your crypto and NFTs."},
  {m:8,t:"Web3",d:"The decentralized, blockchain-based era of the internet."}
] };
