/* ============================================================
   CYBER 2 VOCABULARY DATA — single source of truth.
   Loaded by vocab.html (the Vocabulary Lab) AND ctf.html (Capture the Flag).
   Edit terms here; both pages update. m = module number (1-10).
   ============================================================ */
window.CY2_VOCAB = (function () {
  const MODULES = {
    1:"Threats, Adversaries & Attacks",
    2:"Organizational Security",
    3:"Physical Security",
    4:"Network Attacks & Vulnerabilities",
    5:"Detecting & Protecting Network Attacks",
    6:"Device & Password Vulnerabilities & Attacks",
    7:"Detecting & Protecting from Device & Password Attacks",
    8:"Application & Data Attacks & Vulnerabilities",
    9:"Cryptography",
    10:"Detecting & Protecting from Application & Data Attacks"
  };
  const VOCAB = [
    {m:1,t:"Social Engineering",d:"Using psychological tricks to manipulate people into revealing information, downloading a malicious file, or clicking a malicious link."},
    {m:1,t:"Phishing",d:"A social engineering attack, usually by email or message, that tricks a target into giving up information or clicking a malicious link."},
    {m:1,t:"Pretexting",d:"Creating a believable fake reason to contact a target in order to gain their trust."},
    {m:1,t:"Elicitation",d:"Manipulating someone into revealing sensitive information."},
    {m:1,t:"Adversary",d:"A person or group that carries out a cyberattack."},
    {m:1,t:"Script Kiddie",d:"A low-skilled adversary who uses tools built by others without understanding how they work."},
    {m:1,t:"Hacktivist",d:"An adversary motivated by social, political, or personal causes."},
    {m:1,t:"Insider Threat",d:"An adversary who already has legitimate credentials and access to an organization's systems and data."},
    {m:1,t:"Zero-Day",d:"An undocumented vulnerability that has no patch available yet."},
    {m:1,t:"Reconnaissance",d:"The attack phase in which adversaries gather as much information as possible about a target."},
    {m:1,t:"Open Source Intelligence (OSINT)",d:"Freely available public information that adversaries collect about a target."},
    {m:1,t:"Malware",d:"Malicious software that damages a device or network, or gives an adversary access to it."},
    {m:2,t:"Confidentiality",d:"Ensuring that only authorized individuals, systems, or processes can access data."},
    {m:2,t:"Integrity",d:"Ensuring that data is accurate and trustworthy and has not been altered."},
    {m:2,t:"Availability",d:"Ensuring that data and services are accessible to authorized users when needed."},
    {m:2,t:"Asset",d:"Anything of value to an organization, such as data, money, infrastructure, or reputation."},
    {m:2,t:"Risk",d:"The possibility that a threat exploits a vulnerability to compromise an asset."},
    {m:2,t:"Risk Assessment",d:"Evaluating the likelihood and severity of possible attacks against vulnerabilities."},
    {m:2,t:"Risk Mitigation",d:"Implementing security controls to reduce the likelihood or impact of a risk."},
    {m:2,t:"Residual Risk",d:"The risk that remains after an organization applies avoidance, transference, and mitigation."},
    {m:2,t:"Security Control",d:"A safeguard that protects systems and data; it can be physical, technical, or managerial."},
    {m:2,t:"Managerial Control",d:"Rules, policies, and procedures that specify the security that should be in place."},
    {m:2,t:"Defense in Depth",d:"A layered security strategy using multiple controls so that if one fails, others still protect."},
    {m:2,t:"Preventative Control",d:"A control that stops an adversary from attacking, such as a lock or encryption."},
    {m:2,t:"Detective Control",d:"A control that helps identify attacks when they occur, such as an IDS or camera."},
    {m:2,t:"Corrective Control",d:"A control that fixes problems and restores systems, such as patching or an IPS."},
    {m:3,t:"Piggybacking",d:"Using social engineering to get an authorized person to grant access to a restricted area."},
    {m:3,t:"Tailgating",d:"Following closely behind an authorized person into a restricted area without their knowledge."},
    {m:3,t:"Shoulder Surfing",d:"Watching a user access sensitive information so the adversary can use it later."},
    {m:3,t:"Dumpster Diving",d:"Searching through a target's physical trash for information useful to an attack."},
    {m:3,t:"Card Cloning",d:"Copying an authorized user's access card to gain the access that user has."},
    {m:3,t:"Access Control Vestibule",d:"A two-door entry (mantrap) that prevents an unauthorized person from following someone into a restricted area."},
    {m:3,t:"Bollard",d:"A sturdy post that blocks vehicles from entering a restricted area."},
    {m:3,t:"Card Reader",d:"A device that records and controls which badges are used to access entries and denies unauthorized badges."},
    {m:3,t:"Uninterruptible Power Supply (UPS)",d:"A backup power source that keeps a device running during a power outage."},
    {m:3,t:"Security Awareness Training",d:"Educating employees so they can recognize and help prevent security threats."},
    {m:3,t:"Clean Desk Policy",d:"A policy requiring sensitive documents be cleared from workstations when left unattended."},
    {m:3,t:"Motion Sensor",d:"A detective control that alerts security to movement in an area."},
    {m:4,t:"ARP Poisoning",d:"Sending falsified ARP packets so the adversary's device receives traffic intended for the target."},
    {m:4,t:"MAC Spoofing",d:"Faking a device's MAC address to impersonate a legitimate device."},
    {m:4,t:"MAC Flooding",d:"Overwhelming a switch with many fake MAC addresses to force it to broadcast traffic."},
    {m:4,t:"On-Path Attack (Man-in-the-Middle)",d:"Secretly intercepting and relaying communication between two parties who think they talk directly."},
    {m:4,t:"Eavesdropping (Sniffing)",d:"Capturing and copying data while it is in transit on a network."},
    {m:4,t:"DNS Poisoning",d:"Planting a fake DNS record to redirect users' browsers to a malicious website."},
    {m:4,t:"Credential Harvesting",d:"Using a fake login page that looks real to capture users' credentials."},
    {m:4,t:"Denial of Service (DoS)",d:"An attack that makes a system or resource unavailable to authorized users."},
    {m:4,t:"Distributed Denial of Service (DDoS)",d:"A denial of service attack launched from many devices at the same time."},
    {m:4,t:"Rogue Access Point",d:"An unauthorized wireless access point plugged into a network to gain access to it."},
    {m:4,t:"Evil Twin",d:"A fake wireless access point that imitates a legitimate one to capture victims' traffic."},
    {m:4,t:"Jamming",d:"Flooding an area with a strong signal in the network's frequency to block wireless traffic."},
    {m:4,t:"War Driving",d:"Moving around a target to detect wireless network signals and gather information about them."},
    {m:5,t:"Firewall",d:"Software, on a device or router, that allows or denies network traffic based on rules."},
    {m:5,t:"Stateless Firewall",d:"A firewall that filters traffic using only packet header information like IPs, ports, and protocols."},
    {m:5,t:"Stateful Firewall",d:"A firewall that tracks the state of connections and can filter by connection-related rules."},
    {m:5,t:"Next-Generation Firewall (NGFW)",d:"A firewall with advanced features like intrusion prevention and deep packet inspection."},
    {m:5,t:"Access Control List (ACL)",d:"The ordered set of rules a firewall uses to permit or deny inbound and outbound traffic."},
    {m:5,t:"Network Segmentation",d:"Dividing a network into smaller isolated subnets to limit how far an attack can spread."},
    {m:5,t:"Screened Subnet (DMZ)",d:"A network segment between the internet and internal network that holds public-facing resources."},
    {m:5,t:"VLAN",d:"A logical grouping that separates devices that are physically connected to the same switches."},
    {m:5,t:"Port Security",d:"Limiting the number of MAC addresses allowed on a switch port to prevent MAC flooding."},
    {m:5,t:"WPA3",d:"Currently the strongest wireless encryption protocol."},
    {m:5,t:"VPN",d:"An encrypted tunnel that protects a user's traffic over a public network."},
    {m:5,t:"Network Intrusion Detection System (NIDS)",d:"A tool that analyzes network data for malicious activity and raises an alert."},
    {m:5,t:"Network Intrusion Prevention System (NIPS)",d:"A tool that detects malicious network activity and can also block or stop it."},
    {m:5,t:"SIEM",d:"A system that collects and analyzes data from many sources to detect attacks and raise alerts."},
    {m:6,t:"Virus",d:"Malware that must be activated by a user executing or opening a file."},
    {m:6,t:"Worm",d:"Malware that spreads from one computer to another without human interaction."},
    {m:6,t:"Trojan",d:"Malware embedded in other software that appears harmless."},
    {m:6,t:"Ransomware",d:"Malware that encrypts a device's files and demands payment for the decryption key."},
    {m:6,t:"Spyware",d:"Malware that tracks a user's actions and sends the information back to an adversary."},
    {m:6,t:"Keylogger",d:"Software or hardware that records a user's keystrokes and reports them to an adversary."},
    {m:6,t:"Rootkit",d:"Sophisticated malware that controls the operating system and hides itself from detection."},
    {m:6,t:"Fileless Malware",d:"Malicious code that lives in RAM and uses legitimate installed programs to compromise a device."},
    {m:6,t:"Internet of Things (IoT)",d:"Everyday devices with embedded computers that connect to the internet."},
    {m:6,t:"Brute Force Attack",d:"Using an automated tool to test every possible password a user could have."},
    {m:6,t:"Dictionary Attack",d:"Using an automated tool to test a list of common passwords."},
    {m:6,t:"Rainbow Table Attack",d:"Using a precomputed table of passwords and their hashes to crack a captured hash."},
    {m:6,t:"Password Spraying",d:"Trying a few common passwords against many different user accounts."},
    {m:6,t:"Credential Stuffing",d:"Using stolen or default username and password pairs to break into accounts."},
    {m:7,t:"Hashing",d:"Converting data into a fixed-length, irreversible value called a hash, checksum, or digest."},
    {m:7,t:"Collision",d:"When two different inputs produce the same hash output."},
    {m:7,t:"Salt",d:"Random bits added to a password before hashing so identical passwords get different hashes."},
    {m:7,t:"Multifactor Authentication (MFA)",d:"Requiring two or more independent factors to verify a user's identity."},
    {m:7,t:"Authentication Factor",d:"A category of proof of identity: something you know, have, are, or somewhere you are."},
    {m:7,t:"Biometric Factor",d:"Authentication that measures a physical trait such as a fingerprint, face, or iris."},
    {m:7,t:"Anti-Malware Software",d:"Software that scans for, quarantines, and removes malware using known signatures."},
    {m:7,t:"Signature",d:"A detectable indicator that identifies a specific piece of malware."},
    {m:7,t:"Patch",d:"A small update that fixes a known vulnerability in software."},
    {m:7,t:"Host-Based Firewall",d:"A firewall that runs on an individual device to filter its traffic."},
    {m:7,t:"Account Lockout",d:"Disabling an account after a set number of failed login attempts."},
    {m:7,t:"Indicators of Compromise (IoCs)",d:"Signs in logs or systems that suggest a cyberattack has occurred."},
    {m:8,t:"Data Validation",d:"Verifying that user input meets expected criteria before an application processes it."},
    {m:8,t:"Injection Attack",d:"Inserting unexpected character strings into input fields to alter a program's behavior."},
    {m:8,t:"SQL Injection",d:"Placing SQL commands into an input field to read, change, or delete database data."},
    {m:8,t:"Cross-Site Scripting (XSS)",d:"Injecting malicious code into a website that a user's browser then executes."},
    {m:8,t:"Buffer",d:"A fixed-size section of computer memory that holds input data."},
    {m:8,t:"Buffer Overflow",d:"Feeding more data into memory than allotted, which can crash a system or run malicious code."},
    {m:8,t:"Directory Traversal",d:"Modifying URLs or requests to access files outside a web application's intended folder."},
    {m:8,t:"Privilege Escalation",d:"Gaining a higher level of access than authorized, often by compromising an admin account."},
    {m:9,t:"Cryptography",d:"The practice of hiding information so that only authorized parties can read it."},
    {m:9,t:"Encryption",d:"The process of converting readable information into an unreadable form."},
    {m:9,t:"Decryption",d:"Reversing encryption to retrieve the original information."},
    {m:9,t:"Plaintext",d:"The original readable information before it is encrypted."},
    {m:9,t:"Ciphertext",d:"The unreadable output produced by an encryption algorithm."},
    {m:9,t:"Key",d:"The secret value that is combined with information to encrypt or decrypt it."},
    {m:9,t:"Keyspace",d:"The total number of possible keys; a larger keyspace is harder for an adversary to crack."},
    {m:9,t:"Symmetric Encryption",d:"Encryption that uses the same key to both encrypt and decrypt information."},
    {m:9,t:"Asymmetric Encryption",d:"Encryption that uses a public/private key pair, one key to encrypt and the other to decrypt."},
    {m:9,t:"Public Key",d:"The freely published key in an asymmetric key pair, used to encrypt data to its owner."},
    {m:9,t:"Private Key",d:"The secret key in an asymmetric key pair that must be stored securely to decrypt data."},
    {m:9,t:"AES",d:"The Advanced Encryption Standard, the most common symmetric encryption algorithm."},
    {m:9,t:"RSA",d:"A common asymmetric encryption algorithm used for secure communication and signatures."},
    {m:9,t:"Digital Signature",d:"Cryptographic proof that a message is authentic and has not been altered."},
    {m:9,t:"Block Encryption",d:"Encryption that processes data in fixed-size chunks called blocks."},
    {m:10,t:"Access Control",d:"Enforcing which subjects (users or apps) can access, modify, or remove which objects."},
    {m:10,t:"Role-Based Access Control (RBAC)",d:"Granting access based on a user's assigned role in the organization."},
    {m:10,t:"Rule-Based Access Control (RuBAC)",d:"Granting or denying access based on a set of rules, such as time of day."},
    {m:10,t:"Discretionary Access Control (DAC)",d:"Letting the owner of a resource decide what access other users have to it."},
    {m:10,t:"Mandatory Access Control (MAC)",d:"Strict access based on levels assigned by an administrator, as in the Bell-LaPadula model."},
    {m:10,t:"Principle of Least Privilege",d:"Giving an entity only as much access as it needs to do its job and no more."},
    {m:10,t:"Data States",d:"The three states of data — at rest (stored), in transit (moving), and in use (being processed) — each needing different protection."},
    {m:10,t:"Personally Identifiable Information (PII)",d:"Any data that can identify a person, such as name, SSN, address, or biometrics."},
    {m:10,t:"Protected Health Information (PHI)",d:"Health-related data protected under HIPAA, such as test results and treatment records."},
    {m:10,t:"Input Sanitization",d:"Cleaning user input to remove characters or code that could trigger an attack."},
    {m:10,t:"Secure by Design",d:"Building security into every phase of product development, not just as an add-on feature."},
    {m:10,t:"Secure by Default",d:"Shipping products with their security features already enabled out of the box."},
    {m:1,t:"Password Cracking",d:"Recovering passwords from captured hashes or data, often using automated tools."},
    {m:1,t:"Log Analysis",d:"Examining log files to detect and investigate malicious activity."},
    {m:1,t:"Network Traffic Analysis",d:"Inspecting captured network packets to find suspicious or malicious activity."},
    {m:1,t:"Wireless Access Exploitation",d:"Attacking weaknesses in Wi-Fi networks to gain unauthorized access."},
    {m:1,t:"Scanning and Reconnaissance",d:"Probing a target to map its systems, services, and weaknesses."},
    {m:1,t:"Web Application Exploitation",d:"Abusing flaws in web apps, such as injection or XSS, to compromise them."},
    {m:1,t:"Forensics",d:"Collecting and analyzing digital evidence after a security incident."},
    {m:1,t:"Enumeration",d:"Extracting detailed information like users, shares, and services from a target."},
    {m:1,t:"Exploitation",d:"Using a vulnerability to gain access to or control of a system."},
    {m:1,t:"Metasploit",d:"A widely used framework for developing and running exploits."},
    {m:1,t:"Ethical Hacking",d:"Legally testing systems for vulnerabilities with the owner's permission."},
    {m:1,t:"Penetration Testing",d:"Authorized simulated attacks used to find and fix security weaknesses."},
    {m:2,t:"Separation of Duties",d:"Dividing critical tasks among people so no single person has full control."},
    {m:2,t:"Cloud Computing",d:"Delivering computing services over the Internet instead of on local hardware."},
    {m:2,t:"Risk Management",d:"The overall process of identifying, assessing, and reducing security risks."},
    {m:2,t:"Incident Response",d:"The organized process of detecting, containing, and recovering from an attack."},
    {m:2,t:"Incident Handling",d:"The hands-on steps taken to manage a security incident as it happens."},
    {m:2,t:"Business Continuity",d:"Planning to keep essential operations running during and after a disruption."},
    {m:2,t:"Qualitative Risk Analysis",d:"Rating risk using descriptive levels like low, medium, and high."},
    {m:2,t:"Quantitative Risk Analysis",d:"Rating risk using measurable numbers and dollar amounts."},
    {m:2,t:"NIST Framework",d:"A set of standards and best practices for managing cybersecurity risk."},
    {m:2,t:"Recovery Time Objective (RTO)",d:"The maximum acceptable time to restore a system after an outage."},
    {m:2,t:"Recovery Point Objective (RPO)",d:"The maximum acceptable amount of data loss, measured in time."},
    {m:2,t:"Endpoint Security",d:"Protecting individual devices like laptops and phones from threats."},
    {m:5,t:"Secure Zones",d:"Network areas separated and protected according to their level of trust."},
    {m:7,t:"Authentication",d:"Verifying the identity of a user or device."},
    {m:7,t:"Authorization",d:"Determining what an authenticated user is allowed to do."},
    {m:7,t:"Accounting",d:"Tracking and recording what authenticated users do on a system (the third A in AAA)."},
    {m:7,t:"LDAP",d:"Lightweight Directory Access Protocol — used to access and manage directory information like user accounts."},
    {m:7,t:"Authentication Protocols",d:"Standards such as Kerberos or RADIUS that verify identities on a network."},
    {m:7,t:"Single Sign-On (SSO)",d:"Logging in once to gain access to many related systems."},
    {m:7,t:"Active Directory",d:"A Microsoft service that manages users, computers, and permissions on a network."},
    {m:7,t:"Public Key Infrastructure (PKI)",d:"The system of keys, certificates, and authorities that manages public-key encryption."},
    {m:7,t:"Digital Certificate",d:"An electronic document that proves ownership of a public key."},
    {m:9,t:"Key Management",d:"The secure creation, distribution, storage, and retirement of cryptographic keys."},
    {m:10,t:"Secure Coding",d:"Writing software in ways that avoid common security vulnerabilities."},
    {m:10,t:"Input Validation",d:"Checking that user input is safe and expected before the program processes it."},
    {m:10,t:"Error Handling",d:"Managing errors gracefully so they do not reveal information or crash the app."}
  ];
  return { modules: MODULES, terms: VOCAB };
})();
